### ISSUE TITLE
Exit code when 'nothing to do!'

### ISSUE THREAD

**Issue by jbnicolai** [facebook/PathPicker#102]
When using fpp programmatically the only way to detect it fails is parsing `stdout` for `nothing to do!`.

Would a PR introducing a failure indicating exit code be accepted?

**Comment by pcottle** [comment]
I wouldnt exactly call this an "error exit" but i can see why itd be useful. Let me see if this can easily be done since that output comes from the script we generate...

```
[pcottle:~/Desktop:]$ echo "exit 1" > ./test.sh
[pcottle:~/Desktop:]$ sh ./test.sh && echo "hi"
[pcottle:~/Desktop:]$ sh ./test.sh || echo "hi"
hi
```

ah yeah should work!

**Comment by pcottle** [comment]
```
[pcottle:~/Dropbox (Facebook)/wip/PathPicker:master]$ ./fpp && echo "worked"
Using old result...
nothing to do!
[pcottle:~/Dropbox (Facebook)/wip/PathPicker:master]$ ./fpp || echo "failed"
Using old result...
nothing to do!
failed
```

**Comment by jbnicolai** [comment]
Thanks!

**Comment by pcottle** [comment]
In the 0.5.7 release, adding PR to homebrew now:
https://github.com/facebook/PathPicker/releases/tag/0.5.7
