### ISSUE TITLE
Flag to disable 'Using old result...'

### ISSUE THREAD

**Issue by jbnicolai** [facebook/PathPicker#103]
When using fpp as part of a pipeline you don't want it to fall back to reusing the previous result. See [src/processInput.py#L60](https://github.com/facebook/PathPicker/blob/3d4d8b064eec228ef3950d8c8e5b3287bbe9a987/src/processInput.py#L60)

Would a PR introducing a flag disabling this option potentially be accepted?

**Comment by pcottle** [comment]
@jbnicolai We fall back to using the old result only when we don't receive any new input. If we disabled using the old selection, all we could do is print out the usage command.

What situation are you in where you want that to happen?


maybe its easier to run something like:
```
fpp --clean; fpp
```

that takes care of clearing out the old result / pickled selection / anything else we have? I think thats more straightforward than something like "dont use old result but im not giving you input either so... just print the `usage()` message" with a separate flag.

Open to the PR though if theres something i didnt think of

**Comment by lastquestion** [comment]
I think that @jbnicolai may actually be calling the python processes directly.

**Comment by jbnicolai** [comment]
@pcottle didn't know about `--clean`, that'll serve my purposes just fine :)

@lastquestion my use case is a bit obscure. It's for a tmux plugin ([tmux-fpp](https://github.com/tmux-plugins/tmux-fpp/blob/master/fpp.tmux#L18) which runs `fpp` over the last generated `stdout`

**Comment by pcottle** [comment]
oh whoops @jbnicolai  -- `fpp --clean` doesnt exist yet, but it will soon. let me update this real quick

**Comment by jbnicolai** [comment]
Thanks for the heads-up @pcottle, and no worries. Won't update till tomorrow at the earliest ;-)

**Comment by pcottle** [comment]
In the 0.5.7 release, adding PR to homebrew now:
https://github.com/facebook/PathPicker/releases/tag/0.5.7

**Comment by jbnicolai** [comment]
Thanks!
