### ISSUE TITLE
zsh issue with command mode

### ISSUE THREAD

**Issue by raine** [facebook/PathPicker#125]
Happens when I write git add in the command mode:

```
$ git status | fpp
/Users/rainevi/.zprezto/init.zsh: line 14: autoload: command not found
/Users/rainevi/.zprezto/init.zsh: line 15: print: command not found
/Users/rainevi/commands.zsh: line 1: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
/Users/rainevi/commands.zsh: line 2: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
/Users/rainevi/commands.zsh: line 3: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
/Users/rainevi/commands.zsh: line 15: `mongo-cli': not a valid identifier
```

**Comment by pcottle** [comment]
Hrm -- how do you source your zshrc? does sourcing these files work?

https://github.com/facebook/PathPicker/blob/master/src/output.py#L33

**Comment by raine** [comment]
I'm not sure about the specific, but I use [prezto](https://github.com/sorin-ionescu/prezto)

I source `.zshsecrets` from `.zshrc` and `.zshsecret` sources `commands.zsh`

But the weird thing about that error output is that `commands.zsh` is not in the home directory, but rather in a directory under it.

**Comment by pcottle** [comment]
Hrmmm. If you have a fresh bash script, can it successfully source your `.zshrc` file? something like

```
source ~/.zshrc
echo "success"
```

If you paste that into a `test.sh` and run it, what is the output? im wondering if its something weird with pretzo's configuration setup

**Comment by raine** [comment]
I get the same errors when I do that.

**Comment by pcottle** [comment]
Merged #138 so this is fixed! thanks again @hlian

**Comment by pcottle** [comment]
whoops, this didnt post earlier:
=====

> I get the same errors when I do that.

yeah, so this is an issue with sourcing your zshrc to begin with -- one of the assumptions of `fpp`'s bash execution mode is that we can source all those files :P

let me check out #138 which is probably the better fix

**Comment by raine** [comment]
Awesome.
