### ISSUE TITLE
Objective-C category conventions break path parsing

### ISSUE THREAD

**Issue by dyerw** [facebook/PathPicker#130]
### Description
Objective-C categories are named like so: "NSArray+Utils.h". Path picker doesn't parse these properly and won't let you pick the entire path leading to the file. It only highlights the part after the "+". This creates significant usability issues while using fpp with Objective-C projects.

### Reproduce
In terminal:
```
$ touch NSArray+Utils.h
$ ls | fpp
```

**Comment by pcottle** [comment]
Closed in ~2 hours! Not too shabby :D Thanks for the report @dyerw, originally this would have been a bit scary of a feature to implement but now with filesystem validation and better test coverage, i can merge it more confidently

**Comment by dyerw** [comment]
@pcottle thanks for the quick fix!
