### ISSUE TITLE
Files with spaces in their name are not parsed correctly

### ISSUE THREAD

**Issue by benmccormick** [facebook/PathPicker#145]
When seeing file paths that have a space in them (yes clearly not ideal), fpp cuts off early or starts partway through

![1__scratchworkspace___users_ben_code_windsor_wcui_dev_src_wcui__tmux__and_new_issue_ _facebook_pathpicker](https://cloud.githubusercontent.com/assets/1899941/7897873/d23bf684-06bb-11e5-8c09-27dc01fd29f1.png)

This is with fpp version 0.5.7.  

This image also shows the hyphenated extensions issue from #144

**Comment by pcottle** [comment]
Can you try using 0.6.0 by any chance? We added filesystem validation:
https://github.com/facebook/PathPicker/releases/tag/0.6.0

So we can actually parse files with spaces in them now :) You should be able to upgrade via brew since thats the latest version:
https://github.com/Homebrew/homebrew/blob/master/Library/Formula/fpp.rb

Or just clone the repo and do `brew install ./fpp.rb`

**Comment by pcottle** [comment]
The hyphens stuff will be easy to add, thats just a regex change.

closing this out since im pretty sure we have files with spaces working, but reopen if you can repro on 0.6

**Comment by benmccormick** [comment]
Ah, I checked to see if there was a newer version but forgot to call `brew update` first.

Unfortunately the file system validation seems to remove the false positives but not actually correctly identify that the file with a space in it exists.  

![2__dotfiles__find__pwd___ack_package___fpp__bash_](https://cloud.githubusercontent.com/assets/1899941/7905697/12132d9c-07eb-11e5-8e24-caa1647f5dfb.png)

**Comment by pcottle** [comment]
Are you talking about the `Package Control.user-ca-bundle` files? In order for those to parse, we need both spaces //and// hyphen support, and I just landed the hyphen support in that other task. so try installing from master! should work then. probably will update homebrew by EOW

**Comment by benmccormick** [comment]
None of the files above were selectable except the bottom one.  Does the hyphen issue effect hyphens in  folders as well as extensions?  If not I'd expect `sublime/user-packages/Package Control.cache` to work.

**Comment by pcottle** [comment]
Ah dang ok I'll take another look at this then

**Comment by pcottle** [comment]
Ah this was easy to fix -- just needed to allow extensions to have hyphens in the regex that allows spaces :O woof. #149 should go in clean and then we are good!

**Comment by benmccormick** [comment]
Confirmed that this all looks good now on master.  Thanks!

**Comment by pcottle** [comment]
Great to hear @benmccormick ! :heart_eyes: feel free to drop by and open issues in the future for other bugs / improvements
