### ISSUE TITLE
Commands not working with Ubuntu and dash

### ISSUE THREAD

**Issue by sr105** [facebook/PathPicker#152]
fpp version 0.6.0
My shell is bash, but on "Ubuntu 14.04.2 LTS", /bin/sh is a symlink to /bin/dash.
I get this as an output:

    $ ag 'of_find_node_by_name' include | fpp
    /home/android/.fpp/.fpp.sh: 2: /home/android/.fpp/.fpp.sh: shopt: not found
    /home/android/.fpp/.fpp.sh: 7: /home/android/.fpp/.fpp.sh: source: not found
    /home/android/.fpp/.fpp.sh: 13: /home/android/.fpp/.fpp.sh: source: not found
    executing command:
    e '/android/gw/kernel_imx/include/linux/of.h'
    /home/android/.fpp/.fpp.sh: 17: /home/android/.fpp/.fpp.sh: e: not found

'e' is an executable shell script in ~/bin. If I run "bash .fpp.sh", it works. If I run "sh .fpp.sh", I get the errors you see above.

**Comment by sr105** [comment]
'.' should be used instead of 'source' since '.' means the same thing and is part of the POSIX standard for sh.

Also, if "sh" in the main fpp shell script is replaced with $SHELL, the problem disappears.

**Comment by pcottle** [comment]
Lets merge into #155 since I think this was solved with a recent PR -- You can see we now use `$SHELL` in interactive mode:

https://github.com/facebook/PathPicker/blob/master/fpp#L36

Try installing from master and seeing if the issue persists @sr105
