### ISSUE TITLE
Change tooltip to "Copied!" when copy button is pressed

### ISSUE THREAD

**Issue by engz** [facebook/PathPicker#153]
Provide feedback :)

![screenshot 2015-06-04 20 43 20](https://cloud.githubusercontent.com/assets/919630/7999048/630892b6-0afa-11e5-8f75-98ba749e54a4.png)

**Comment by pcottle** [comment]
![Wooo](http://g.recordit.co/XypYWz6zZD.gif)

**Comment by engz** [comment]
Yay!!

**Comment by pcottle** [comment]
Yeah its unfortunate we have to change the position of the tooltip manually (which wouldnt work if we supported other locales) but GitHub might do something similar (or call into the hook that bootstrap exposes)
