### ISSUE TITLE
Commands not working with ZSH and Oh-my-zsh

### ISSUE THREAD

**Issue by Muffo** [facebook/PathPicker#155]
When I try to run a command on a selection I always get this error:

```
> git status -uno | fpp

/root/.oh-my-zsh/oh-my-zsh.sh: line 13: syntax error near unexpected token `('
/root/.oh-my-zsh/oh-my-zsh.sh: line 13: `for config_file ($ZSH/lib/*.zsh); do'
/root/.zshrc: line 123: unsetopt: command not found
/etc/bash_completion.d/git: line 126: syntax error near unexpected token `<'
/etc/bash_completion.d/git: line 126: ` done < <(git config -z --get-regexp '^(svn-remote\..*\.url|bash\.showupstream)$' 2>/dev/null | tr '\0\n' '\n ')'
/etc/bash_completion.d/grub: line 417: `_grub_mkpasswd-pbkdf2': not a valid identifier
```

**Comment by pcottle** [comment]
@Muffo can you run `fpp --version` for me and attach that? We used to try sourcing the rc files but switched to running the shell in interactive mode, which is a safer option. If this happens on a legacy pathpicker client I wouldn't be surprised, but the new interactive shell mode fix should work.

PathPicker should certainly work with just plain zsh regardless though

**Comment by Muffo** [comment]
@pcottle thanks for the reply.

Here is the output of `fpp --version`:

```
> fpp --version
fpp version 0.6.0
```

I have also [asked help on Stackoverflow](http://stackoverflow.com/questions/30667504/facebook-pathpicker-does-not-work-with-zsh) and they have replied me saying I was probably sourcing zsh scripts from bash.

I have checked my `~/.bash_profile` and `~/.bashrc` but I didn't see any trace of the zsh scripts.

I haven't fully understood one of the comment about fpp being written in pure Python, but maybe it makes more sense to you...

**Comment by Muffo** [comment]
Here is the output of /bin/bash -x "$(whence fpp)" that I was suggested to run:

```
> /bin/bash -x "$(whence fpp)"
+ SOURCE=/usr/local/bin/fpp
+ '[' -h /usr/local/bin/fpp ']'
+++ dirname /usr/local/bin/fpp
++ cd -P /usr/local/bin
++ pwd
+ BASEDIR=/usr/local/bin
++ readlink /usr/local/bin/fpp
+ SOURCE=/usr/local/PathPicker/fpp
+ [[ /usr/local/PathPicker/fpp != /* ]]
+ '[' -h /usr/local/PathPicker/fpp ']'
+++ dirname /usr/local/PathPicker/fpp
++ cd -P /usr/local/PathPicker
++ pwd
+ BASEDIR=/usr/local/PathPicker
+ PYTHONCMD=python
+ doProgram
+ python /usr/local/PathPicker/src/processInput.py
Using old result...
+ exec
+ python /usr/local/PathPicker/src/choose.py
+ sh /root/.fpp/.fpp.sh
```


This is the content of /root/.fpp/.fpp.sh:
```
shopt -s expand_aliases
if [ -f ~/.zshrc ]; then
  source ~/.zshrc
fi
if [ -f ~/.bashrc ]; then
  source ~/.bashrc
fi
if [ -f ~/.bash_profile ]; then
  source ~/.bash_profile
fi
if [ -f ~/.bash_aliases ]; then
  source ~/.bash_aliases
fi
echo "executing command:"
echo "ls '/root/myfile'"
ls '/root/myfile'
```

Here is where I am sourcing the `~/.zshrc` and causing the error.

**Comment by pcottle** [comment]
Ah yes, the source of the .fpp.sh is the smoking gun here. We already landed the fix for this in master but we shouldn't be sourcing any rc files directly.

You should be able to install from master to get the fix (see readme instructions) but I'll submit a new minor release, since I'm surprised that this didn't make it in

**Comment by pcottle** [comment]
Alright PR submitted to homebrew:
https://github.com/Homebrew/homebrew/pull/40501

And release made:
https://github.com/facebook/PathPicker/releases/tag/0.6.1

You can also install easily via homebrew by just cloning the repo and `brew install ./fpp.rb` (using the local file) once you are in the directory.

closing this out since the fix is out now!

**Comment by Muffo** [comment]
Thanks a lot @pcottle !

I'll try it tomorrow :+1:

**Comment by pcottle** [comment]
No problem! This task was a good forcing function for me to get the fix out the door. My homebrew PR got merged so after `brew update` you should be good to go
