### ISSUE TITLE
Provide manpage?

### ISSUE THREAD

**Issue by sethwoodworth** [facebook/PathPicker#160]
You have a decent `-h` option via argparse that ultimately appends a lot of multiline strings from [this file](https://github.com/facebook/PathPicker/blob/70de9885f12cc58c7356e7b4f2d361b5c5ed33b4/src/usageStrings.py) into a help statement.  I would find it handy to be able to read this in my `man` program rather than via `-h` and it would make `fpp` easier to include in debian/ubuntu.

How would the maintainers of this project be willing/interested in some glue code in your debian build script to generate and package a manpage?

**Comment by pcottle** [comment]
> How would the maintainers of this project be willing/interested in some glue code in your debian build script to generate and package a manpage?

Yeah certainly! This came up in #117 but @pallavagarwal07 commented saying that the format for man pages is fairly strict. Do you think its tractable to transform our `--help` output into a manpage somehow?

I don't necessarily want to maintain a whole separate stack of help code but if we can integrate it easily with some glue code then I'm down

**Comment by pallavagarwal07** [comment]
@pcottle Now that more people think that this is needed, should I start working?

**Comment by pallavagarwal07** [comment]
I am ready to help, if needed.

**Comment by sethwoodworth** [comment]
Great!

I've reworked a bit of the existing strings. I preserved all of the exportable string variables from USAGE_* but have added more of my own.  I am generating an asciidoc markup file as an intermediary step and using `a2x` from asciidoc to generate a manpage.

Is requiring asciidoc to occasionally regenerate the manpage an issue?  Also, where should `fpp.1` go for the sake of debian packaging?

**Comment by pallavagarwal07** [comment]
@sethwoodworth 
fpp.1 would go in ```debian/usr/share/man/man1 ```.

**Comment by pcottle** [comment]
Thanks a bunch for the PR!

I think the extra dependency is fine since it's only for dev. It would be nice to comment in the script with the right error message if it's not installed

**Comment by sethwoodworth** [comment]
Good idea, script now throws an error message if a2x isn't installed.  And CLA signed.

**Comment by pcottle** [comment]
Closed out in #161 , thanks a bunch again! woooo linux support
