### ISSUE TITLE
installation problems with provided DEB-package 

### ISSUE THREAD

**Issue by eox-cs1** [facebook/PathPicker#162]
Hi ,  
I wanted to install your provided deb-package on an Ubuntu 14.04.2 machine. But the the installed gave me the following errors/warnings:

The package is of bad quality
The installation of a package which violates the quality standards isn't allowed. This could cause serious problems on your computer. Please contact the person or organisation who provided this package file and include the details beneath.
Details:
Lintian check results for /tmp/fpp-1.deb:
mismatching contents of index files: 16:10 ./usr/share/doc/ ./ at /usr/share/lintian/collection/scripts line 37.
warning: collect info scripts about package pathpicker failed
warning: skipping check of binary package pathpicker
mismatching contents of index files: 16:10 ./usr/share/doc/ ./ at /usr/share/lintian/collection/md5sums line 52.
warning: collect info md5sums about package pathpicker failed
warning: skipping check of binary package pathpicker
mismatching contents of index files: 16:10 ./usr/share/doc/ ./ at /usr/share/lintian/collection/file-info line 67.
warning: collect info file-info about package pathpicker failed
warning: skipping check of binary package pathpicker

It would be great if you can correct these...

best regards

**Comment by pcottle** [comment]
Hrm, @pallavagarwal07 did this come up in your testing? or @sethwoodworth was this apparent when you worked on the manpage stuff?

I don't have a ubuntu machine handy so I can't easily repro, but these are mainly just warnings right? We don't really have any binaries so doing those checks wouldn't make sense. Can't tell how serious the others are

**Comment by pallavagarwal07** [comment]
Actually I did point these out. These warnings are only occurring when the packaging is done on a mac. When I use the exact same script on Linux, the packages give a clean lintian output.

**Comment by sethwoodworth** [comment]
I can build the .deb and install it on my machine (debian jessie) without any issue.

I recommend building your .deb files using [travis releases](http://docs.travis-ci.com/user/deployment/releases/)

**Comment by pcottle** [comment]
> Actually I did point these out. These warnings are only occurring when the packaging is done on a mac. When I use the exact same script on Linux, the packages give a clean lintian output.

sweet, lets close this out then. mac users wont be the main customers of the debian packages and these arent a blocker anyways

**Comment by pallavagarwal07** [comment]
@pcottle 
I think you misunderstood. The errors are because the packages are created on Mac, not because of installing on one. 
Anyway, I did check, and the warnings shouldn't cause any real trouble

**Comment by pcottle** [comment]
Ah yeah I misread -- maybe I can reach out to coworkers to get them to build the packages when we have releases :/ actually our devservers are Debian I think so I'll try that next time
