### ISSUE TITLE
PathPicker pollutes user home directory

### ISSUE THREAD

**Issue by vitaut** [facebook/PathPicker#17]
PathPicker creates multiple files in the user home directory:

```
$ ls .fb*
.fbPager.log  .fbPager.pickle  .fbPager.selection.pickle  .fbPager.sh
```

Normally such files are stored under `$HOME/.local/share` or `$HOME/.config` directory on Linux. Please see [XDG Base Directory Specification](http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html) for details.

**Comment by pcottle** [comment]
Yeah I have been meaning to get around to this -- totally can as well. a few questions for you @vitaut:

* is the current user always guaranteed to have write capabilities into `$HOME/.local/share`? one of the nice things about the home directory is not having to worry about user permissions
* is it guaranteed to exist? or will we have to `mkdir -p` beforehand?

I'd love to resolve this though, and it shouldnt be hard since these are all constants in the code

**Comment by vitaut** [comment]
Although all systems I've been working on have writable `$HOME/.local/share`, I can't say whether this directory is guaranteed to exist, so it's probably safer to check and create if it doesn't.

On a closer inspection though`.fbPager*` files look more like temporary files (are they?) rather than some user-specific settings and could probably be stored in `/tmp`.

**Comment by pcottle** [comment]
yeah they are all temporary -- the only one that persists between sessions is the selection pickle and if thats gone its nbd.

same question -- is `/tmp` always guaranteed to be writeable? or on average more guaranteed to be writeable and exist compared to a home dir?

**Comment by vitaut** [comment]
I think it's safe to assume that `/tmp` is writable.

**Comment by pcottle** [comment]
Alright -- this is coming tomorrow!

we'll be sharing the same pickle selection across users on the same machine, so maybe we should prepend by the username? `pwd.getpwuid(os.getuid()).pw_name`

**Comment by zkanda** [comment]
I think it's safe to assume that everything under the users directory is owned by the user.

A lot of projects is either using $HOME/.config or a dedicated folder in home:
E.g.
![screen shot 2015-05-09 at 11 35 00 pm](https://cloud.githubusercontent.com/assets/5354184/7550845/16c19746-f6a4-11e4-975c-774a62eb44bd.png)

**Comment by lastquestion** [comment]
`$HOME/.fpp` is preferable to me... that way `fpp` doesn't have to deal with user issues.
proposed PR: https://github.com/facebook/PathPicker/pull/77

**Comment by pcottle** [comment]
Fixed by #77 !

**Comment by mcchrish** [comment]
Should it be possible to define a custom FPP_DIR environment variable? Say, I want to move it to `$HOME/.config/fpp`.

**Comment by pcottle** [comment]
Yeah I would be fine with that -- would accept the PR as long as it has a sane default and some basic test coverage (and would be in the help output). We have a number of env variables right now but so far its manageable

**Comment by vitaut** [comment]
:+1: for `$HOME/.config/fpp`. Adding another, even hidden, directory in `$HOME` just for one application looks like an overkill.

**Comment by SamHasler** [comment]
Would supporting XDG_CONFIG_HOME if it's set give more users a cleaner home
dir by default?

**Comment by vitaut** [comment]
@SamHasler `XDG_CONFIG_HOME` may not be set by default (it is not set on Ubuntu 14.04 for instance).

**Comment by SamHasler** [comment]
I know. I'm just saying if XDG_CONFIG_HOME is set, use it, as that's where
that user keeps their config.
