### ISSUE TITLE
Add executed command to shell history

### ISSUE THREAD

**Issue by saveriomiroddi** [facebook/PathPicker#171]
It would be helpful if the executed command would be [optionally] added to the shell history.

If one needs to repeat the command executed by PP, the workflow is very slow compared to just typing Up arrow and Enter, especially when a custom command is used.

**Comment by pcottle** [comment]
> It would be helpful if the executed command would be [optionally] added to the shell history

yeah I totally agree @saveriomiroddi! I think we looked into this briefly when starting the tool but I must not have found the `history -s` command, which seems to do exactly this.

lets see if I can add this to the bash script we execute. my only worry is that it will be in a separate context, so it wont affect your own history

**Comment by pcottle** [comment]
:crying_cat_face: :cry: Yeah, this isn't possible since the `history` command modifies the subshell, not the shell its called from:

```
[pcottle:~/Dropbox (Facebook)/wip/PathPicker:master]$ ./fpp
Using previous input piped to fpp...
executing command:
cat '/Users/pcottle/Dropbox (Personal)/wip/MinCalTrain/src/js/views/DepartureSelectView.js' '/Users/pcottle/Dropbox (Personal)/wip/MinCalTrain/src/js/views/StationSelectView.js' | wc -l
     284
Adding to command history...
[pcottle:~/Dropbox (Facebook)/wip/PathPicker:master]$ cat ~/.fpp/.fpp.sh 
if type shopt > /dev/null; then
  shopt -s expand_aliases
fi

echo "executing command:"
echo "cat '/Users/pcottle/Dropbox (Personal)/wip/MinCalTrain/src/js/views/DepartureSelectView.js' '/Users/pcottle/Dropbox (Personal)/wip/MinCalTrain/src/js/views/StationSelectView.js' | wc -l"
cat '/Users/pcottle/Dropbox (Personal)/wip/MinCalTrain/src/js/views/DepartureSelectView.js' '/Users/pcottle/Dropbox (Personal)/wip/MinCalTrain/src/js/views/StationSelectView.js' | wc -l
echo "Adding to command history..."
history -s "cat '/Users/pcottle/Dropbox (Personal)/wip/MinCalTrain/src/js/views/DepartureSelectView.js' '/Users/pcottle/Dropbox (Personal)/wip/MinCalTrain/src/js/views/StationSelectView.js' | wc -l"
```

after I ran the above, the command wasn't added :-/

If anyone has suggestions on how to do this lemme know, but I think i'll have to close out in the meantime

**Comment by oalders** [comment]
@pcottle Would it be reasonable to have `fpp` log it's history to some arbitary file like `~/.fpp/.fpp_history`? At that point it would be trivial to get the last line and re-execute it.  Personally, I'd prefer having a global history over having none at all.

**Comment by oalders** [comment]
Although I now see that `sh ~/.fpp/.fpp.sh` basically gets me to the same place.

**Comment by pcottle** [comment]
> Although I now see that sh ~/.fpp/.fpp.sh basically gets me to the same place.

yeah exactly, this should be exactly that (the last command run, plus some setup code). actually it would be somewhat trivial to alias `fpp` to actually execute `fpp` and then cat one of the lines to the actual bash history (but thats only possible with a top-level alias, nothing our code can control i believe)

my hesitation for a history file is then you have to worry about unbounded size, what number of lines to truncate at, a config option for the former, etc etc.

lemme know if ` sh ~/.fpp/.fpp.sh` doesnt solve what you want though!

**Comment by oalders** [comment]
I've lived with this for a couple of days and it _mostly_ takes care of my needs, but I sometimes find that I need to re-execute the command previous to the last one I just used, so that's the biggest shortcoming for me so far.

I understand that adding a history file would bring some added complexity.  I think that's a valid concern.  I'll have a look at your suggestion to alias `fpp` and try and `cat` something to my bash history.  If I come up with something useful, I'll post it here as an example.

**Comment by pcottle** [comment]
Cool! lemme know

**Comment by oalders** [comment]
This is what I now have in my `.bashrc`. Seems to be working well and it's really speeding up my workflow.  Thanks very much for the suggestion (and for your work on this utility).

```bash
function fpp() {
    local fpp=$(type -fp fpp)

    HISTORY_FILE="$HOME/.fpp/.fpp_history"
    FPP_CACHE="$HOME/.fpp/.fpp.sh"

    # fpp --history just displays entire history prefixed by line numbers
    # fpp --redo will rexec the last entry in the history file
    # fpp --redo -1 will rexec the last entry in the history file
    # fpp --redo -2 will re-exec the second last line in the history file
    # fpp --redo 11 will re-exec entry number 11 in the history file
    case "$1" in
        --history)
        cat --number $HISTORY_FILE
        return 1
        ;;
        --redo)
        if [ $2 ] ; then
            if [ $2 \> 0 ] ; then
                LAST_HISTORY_LINE=$(head -n $2 $HISTORY_FILE |tail -n1)
            else
                LINE_NUMBER=$(( $2 * -1))
                LAST_HISTORY_LINE=$(tail $HISTORY_FILE -n $LINE_NUMBER | head -n1)
            fi
        else
            LAST_HISTORY_LINE=$(tail $HISTORY_FILE -n 1)
        fi

        eval $LAST_HISTORY_LINE
        return 1
        ;;
    esac

    $fpp "$@"
    LAST_COMMAND=$(tail $FPP_CACHE -n 1)

    # Don't keep adding the same command to the history file.
    if [ "$LAST_COMMAND" != "$LAST_HISTORY_LINE" ] ; then
        echo $LAST_COMMAND >> $HISTORY_FILE
    fi
}
```

The code lives at https://github.com/oalders/dot-files/blob/8dcf2bf7911d02fa070f1eae0e95cb126292089c/bashrc#L147

**Comment by pcottle** [comment]
Oooh, I like the implementation of prepending all the history by line number so its easy to reference a previous one. if we get more requests for history functionality i might steal this implementation :)

**Comment by oalders** [comment]
Stealing is good.  :)  My implementation above turned out to be buggy and also based on an older version of `fpp`.  I've updated the comments.  I've also written a short blog post about it: http://www.olafalders.com/2016/01/14/adding-history-to-fpp-facebook-pathpicker/

**Comment by saveriomiroddi** [comment]
For reference, there is a st00pid-easy solution:

    alias fph='fpp && history -s $(tail -n 2 $HOME/.fpp/.fpp.sh | head -n 1)'

It's good enough to accomplish the task; it can also be recycled in other aliases (eg. git ones).

**Comment by oalders** [comment]
@saveriomiroddi thanks for pointing that out!
