### ISSUE TITLE
makeManpage errors out on FreeBSD 10.1 with xmllint

### ISSUE THREAD

**Issue by yggdr** [facebook/PathPicker#175]
```
$ scripts/makeManpage.sh
a2x: WARNING: --destination-dir option is only applicable to HTML based outputs
a2x: ERROR: "xmllint" --nonet --noout --valid "/storage/code/PathPicker/debian/usr/share/man/man1/manpage.xml" returned non-zero exit status 4
gzip: can't stat: ./debian/usr/share/man/man1/fpp.1: No such file or directory

$ xmllint --version
xmllint: using libxml version 20902
   compiled with: Threads Tree Output Push Reader Patterns Writer SAXv1 FTP HTTP DTDValid HTML Legacy C14N Catalog XPath XPointer XInclude Iconv ISO8859X Unicode Regexps Automata Expr Schemas Schematron Modules Debug Zlib Lzma
```

**Comment by pcottle** [comment]
Hrm, I'm going to call on the linux expert-in-residence @pallavagarwal07 and @sethwoodworth who added the script. You guys have any ideas?

**Comment by pallavagarwal07** [comment]
@yggdr
From which directory were you running the script?

**Comment by sethwoodworth** [comment]
Can you gist the output of `xmllint --nonet --noout --valid
"/storage/code/PathPicker/debian/usr/share/man/man1/manpage.xml` please?

**Comment by yggdr** [comment]
I'm running the script either from its own directory, or from the git root.

https://gist.github.com/yggdr/4eb89dd1b4ffb028a6bc
(I can manually download the DTD just fine.)

**Comment by yggdr** [comment]
Just tried it again on FreeBSD 11.0 and it works fine now, so I'm closing this.
