### ISSUE TITLE
FPP prepends `~/www` to filenames?

### ISSUE THREAD

**Issue by derryl** [facebook/PathPicker#180]
For some reason, when I run commands against files, it pre-pends `~/www/` to the filename, rather than running it with the original path. Therefore, no commands work (unless I happened to be inside that directory, which doesn't actually exist) 

Is there a way to override this somewhere? So that it uses the paths I give it, without modification?

**Comment by pcottle** [comment]
@derryl What version of FPP are you running? should be able to find out with `fpp --version`

We used to return `~/www/` as the repo path if we couldnt detect a git or mercurial repository, but we changed that in e302f16118e0a9bbd38b202e1d892a68b30f227c:
https://github.com/facebook/PathPicker/blob/master/src/parse.py#L159

so now you shouldnt be getting `~/www` at all.

**Comment by pcottle** [comment]
Im pretty sure this is just due to an old version, but please reopen if you are getting it after upgrading :+1:

**Comment by derryl** [comment]
@pcottle That did the trick! :blush: Thanks for the swift response -- FPP is a wonderful tool, keep up the great work.

**Comment by pcottle** [comment]
Great! Glad to hear you're unblocked and enjoy the tool -- I'm just glad we can give back to the OSS community
