### ISSUE TITLE
Support ls

### ISSUE THREAD

**Issue by baest** [facebook/PathPicker#183]
Not all files are selectable in ls.

If a do a ls in PathPicker I get:

assets/  CONTRIBUTING.md  debian/  fpp*  fpp.rb  index.html  LICENSE  PATENTS  README.md  scripts/  src/

fpp doesn't pick up:

fpp*
LICENSE
PATENTS

ls --color=always doesn't help

My options for ls is "ls -F --color=auto" and the OS is Ubuntu 12.04

**Comment by baest** [comment]
I'm "attaching" the .pickle file after doing a "ls -F --color=auto | fpp -r":
(dp0
I0
ccopy_reg
_reconstructor
p1
(cformat
SimpleLine
p2
c__builtin__
object
p3
Ntp4
Rp5
(dp6
S'index'
p7
I0
sS'controller'
p8
NsS'formattedLine'
p9
g1
(cformattedText
FormattedText
p10
g3
Ntp11
Rp12
(dp13
S'plainText'
p14
S'assets/'
p15
sS'text'
p16
g15
sS'segments'
p17
(lp18
S''
p19
ag15
asbsbsI1
g1
(cformat
LineMatch
p20
g3
Ntp21
Rp22
(dp23
g7
I1
sS'selected'
p24
I00
sS'end'
p25
I15
sS'hovered'
p26
I00
sg9
g1
(g10
g3
Ntp27
Rp28
(dp29
g14
S'CONTRIBUTING.md'
p30
sg16
g30
sg17
(lp31
g19
ag30
asbsS'afterText'
p32
g1
(g10
g3
Ntp33
Rp34
(dp35
g14
g19
sg16
Nsg17
(lp36
g19
ag19
asbsS'beforeText'
p37
g1
(g10
g3
Ntp38
Rp39
(dp40
g14
g19
sg16
Nsg17
(lp41
g19
ag19
asbsS'start'
p42
I0
sg8
NsS'num'
p43
I0
sS'file'
p44
S'./CONTRIBUTING.md'
p45
sS'originalFile'
p46
g30
sS'decoratedMatch'
p47
g1
(g10
g3
Ntp48
Rp49
(dp50
g14
S'CONTRIBUTING.md'
p51
sg16
S'\x1b[30;40;4mCONTRIBUTING.md'
p52
sg17
(lp53
g19
ag19
aS'30;40;4'
p54
aS'CONTRIBUTING.md'
p55
asbsS'group'
p56
g30
sS'isTruncated'
p57
I00
sbsI2
g1
(g2
g3
Ntp58
Rp59
(dp60
g7
I2
sg8
Nsg9
g1
(g10
g3
Ntp61
Rp62
(dp63
g14
S'debian/'
p64
sg16
g64
sg17
(lp65
g19
ag64
asbsbsI3
g1
(g2
g3
Ntp66
Rp67
(dp68
g7
I3
sg8
Nsg9
g1
(g10
g3
Ntp69
Rp70
(dp71
g14
S'fpp*'
p72
sg16
g72
sg17
(lp73
g19
ag72
asbsbsI4
g1
(g20
g3
Ntp74
Rp75
(dp76
g7
I4
sg24
I00
sg25
I6
sg26
I00
sg9
g1
(g10
g3
Ntp77
Rp78
(dp79
g14
S'fpp.rb'
p80
sg16
g80
sg17
(lp81
g19
ag80
asbsg32
g1
(g10
g3
Ntp82
Rp83
(dp84
g14
g19
sg16
Nsg17
(lp85
g19
ag19
asbsg37
g1
(g10
g3
Ntp86
Rp87
(dp88
g14
g19
sg16
Nsg17
(lp89
g19
ag19
asbsg42
I0
sg8
Nsg43
I0
sg44
S'./fpp.rb'
p90
sg46
g80
sg47
g1
(g10
g3
Ntp91
Rp92
(dp93
g14
S'fpp.rb'
p94
sg16
S'\x1b[30;40;4mfpp.rb'
p95
sg17
(lp96
g19
ag19
aS'30;40;4'
p97
aS'fpp.rb'
p98
asbsg56
g80
sg57
I00
sbsI5
g1
(g20
g3
Ntp99
Rp100
(dp101
g7
I5
sg24
I00
sg25
I10
sg26
I00
sg9
g1
(g10
g3
Ntp102
Rp103
(dp104
g14
S'index.html'
p105
sg16
g105
sg17
(lp106
g19
ag105
asbsg32
g1
(g10
g3
Ntp107
Rp108
(dp109
g14
g19
sg16
Nsg17
(lp110
g19
ag19
asbsg37
g1
(g10
g3
Ntp111
Rp112
(dp113
g14
g19
sg16
Nsg17
(lp114
g19
ag19
asbsg42
I0
sg8
Nsg43
I0
sg44
S'./index.html'
p115
sg46
g105
sg47
g1
(g10
g3
Ntp116
Rp117
(dp118
g14
S'index.html'
p119
sg16
S'\x1b[30;40;4mindex.html'
p120
sg17
(lp121
g19
ag19
aS'30;40;4'
p122
aS'index.html'
p123
asbsg56
g105
sg57
I00
sbsI6
g1
(g2
g3
Ntp124
Rp125
(dp126
g7
I6
sg8
Nsg9
g1
(g10
g3
Ntp127
Rp128
(dp129
g14
S'LICENSE'
p130
sg16
g130
sg17
(lp131
g19
ag130
asbsbsI7
g1
(g2
g3
Ntp132
Rp133
(dp134
g7
I7
sg8
Nsg9
g1
(g10
g3
Ntp135
Rp136
(dp137
g14
S'PATENTS'
p138
sg16
g138
sg17
(lp139
g19
ag138
asbsbsI8
g1
(g20
g3
Ntp140
Rp141
(dp142
g7
I8
sg24
I00
sg25
I9
sg26
I00
sg9
g1
(g10
g3
Ntp143
Rp144
(dp145
g14
S'README.md'
p146
sg16
g146
sg17
(lp147
g19
ag146
asbsg32
g1
(g10
g3
Ntp148
Rp149
(dp150
g14
g19
sg16
Nsg17
(lp151
g19
ag19
asbsg37
g1
(g10
g3
Ntp152
Rp153
(dp154
g14
g19
sg16
Nsg17
(lp155
g19
ag19
asbsg42
I0
sg8
Nsg43
I0
sg44
S'./README.md'
p156
sg46
g146
sg47
g1
(g10
g3
Ntp157
Rp158
(dp159
g14
S'README.md'
p160
sg16
S'\x1b[30;40;4mREADME.md'
p161
sg17
(lp162
g19
ag19
aS'30;40;4'
p163
aS'README.md'
p164
asbsg56
g146
sg57
I00
sbsI9
g1
(g2
g3
Ntp165
Rp166
(dp167
g7
I9
sg8
Nsg9
g1
(g10
g3
Ntp168
Rp169
(dp170
g14
S'scripts/'
p171
sg16
g171
sg17
(lp172
g19
ag171
asbsbsI10
g1
(g2
g3
Ntp173
Rp174
(dp175
g7
I10
sg8
Nsg9
g1
(g10
g3
Ntp176
Rp177
(dp178
g14
S'src/'
p179
sg16
g179
sg17
(lp180
g19
ag179
asbsbs.

**Comment by pcottle** [comment]
Hey @baest , yeah this is unfortunately a known issue :-/ it cant pick up things that //dont// look like files (like the `fpp*` which is a symbolic link i believe), or words that are all caps without any extensions or leading paths.

You can see what we support here:
https://github.com/facebook/PathPicker/blob/master/src/__tests__/testParsing.py#L20
