### ISSUE TITLE
Getting error use 'exit' to exit.

### ISSUE THREAD

**Issue by slackorama** [facebook/PathPicker#190]
I get the following output when I run `fpp` in `zsh`.

     > git st -uno | ~/projects/PathPicker/fpp 
     /home/slack/.fpp/.fpp.sh:zsh:3: use 'exit' to exit.
     /home/slack/.fpp/.fpp.sh:zsh:3: use 'exit' to exit.
     /home/slack/.fpp/.fpp.sh:zsh:3: use 'exit' to exit.
     /home/slack/.fpp/.fpp.sh:zsh:3: use 'exit' to exit.
     /home/slack/.fpp/.fpp.sh:zsh:3: use 'exit' to exit.
     /home/slack/.fpp/.fpp.sh:zsh:3: use 'exit' to exit.
     /home/slack/.fpp/.fpp.sh:zsh:3: use 'exit' to exit.
     /home/slack/.fpp/.fpp.sh:zsh:3: use 'exit' to exit.
     /home/slack/.fpp/.fpp.sh:zsh:3: use 'exit' to exit.

My version info:

    ; ~/projects/PathPicker/fpp --version
    fpp version 0.6.1

My `.fpp.sh` file just looks like:

    emacsclient --no-wait '/home/slack/projects/base/lib/perl/Mon/Elasticsearch.pm'

When I manually set `VIMRUNTIME=1` it works without the error. I'm just running it inside of xterm.

**Comment by slackorama** [comment]
This fixes it but I'm unsure if it'll break other use cases?

    diff --git a/src/output.py b/src/output.py
    index a5cb491..ad547c0 100644
    --- a/src/output.py
    +++ b/src/output.py
    @@ -43,6 +43,7 @@ def execComposedCommand(command, lineObjs):
         appendAliasExpansion()
         appendIfInvalid(lineObjs)
         appendFriendlyCommand(command)
    +    appendToFile('exit 0')
     
     
     def editFiles(lineObjs):
    @@ -54,6 +55,7 @@ def editFiles(lineObjs):
         command = joinEditCommands(partialCommands)
         appendIfInvalid(lineObjs)
         appendToFile(command)
    +    appendToFile('exit 0')
     
     
     # Private helpers

**Comment by pcottle** [comment]
for the editor case it's easy to add `exit 0` and have it work, but for the command case we should properly propagate up the exit code if its non-zero. i was about to suggestion doing just a `&& exit 0` but that will break if people have `;` after their command.

could we just check the exit code of the last command and use that?

```
exit $?;
```

I'd be down for a PR that does that -- should be safe!

**Comment by slackorama** [comment]
Thanks for checking my logic. Good point about the commands.

I'll put a PR together and send it along.

Thanks for path picker by the way. Saves me tons of copy pasta.

**Comment by pcottle** [comment]
:+1: :+1: :+1: PR would be awesome.

I'm glad you find it useful too! Eliminating copy pasta and not having to use the mouse as much wer ebig motivators for me to finish it
