### ISSUE TITLE
Doesn't jump to line number when using neovim

### ISSUE THREAD

**Issue by jeffkile** [facebook/PathPicker#193]
Since I upgrade vim to neovim fpp stopped jumping to the line number of the selected item, instead it just opens the file and stops at the first line.

**Comment by pcottle** [comment]
Hey @jeffkile do you know the command line formatting for `neovim`'s line number args? We have a manual mapping here:
https://github.com/facebook/PathPicker/blob/371ffc2d8df002e16e7e063ce218023280fab50d/src/output.py#L95

and neovim has an entry. does that not work? can you output ` ~/.fpp/.fpp.sh`?

**Comment by jeffkile** [comment]
Yeah that manual mapping is wrong. It should be this
```
    if editor in ['vim', 'nvim'] and lineNum != 0:
        return '\'%s\' +%d' % (filePath, lineNum)
    elif editor in ['vi', 'nano', 'joe', 'emacs'] and lineNum != 0:
        return '+%d \'%s\'' % (lineNum, filePath)
```

Can I submit a pull request?

**Comment by pcottle** [comment]
certainly! Would be much appreciated :) cc @pallavagarwal07 just as an fyi. i shoulda double checked in diff review though

**Comment by pallavagarwal07** [comment]
That's weird. I've been using neovim for over 6 months and it supports both
`nvim +17 'file.c'`
and
`nvim 'file.c' +17` formats.

**Comment by pcottle** [comment]
hrm, might be version dependent then? @jeffkile what version are you running?

**Comment by jeffkile** [comment]
`NVIM 0.0.0-alpha+201508100001 (compiled Aug 11 2015 10:53:00)` 
I'm using using Fish, tmux and OSX as well.

I just tried it from the command line and oddly enough both ways @pallavagarwal07 suggested work fine for me ... but only from the command line. When using FPP only the line number after the file name works for me.

Should I still push up the PR or should I look in to this further?

**Comment by pcottle** [comment]
Have you outputted your `$FPP_EDITOR` or `$VISUAL`? we use those environment variables before falling back to `$EDITOR`. that might be the difference in behavior

or output the `~/.fpp/.fpp.sh` and paste it here so we can compare exactly

**Comment by pallavagarwal07** [comment]
@jeffkile Could you ensure that the file is being opened in nvim (`:version` after opening file via fpp)? It might be not obvious if both vim and nvim use the same vimrc and maybe it's reading nvim environment variable and thus nvim format but attempting to open the file finally with vim?

**Comment by pcottle** [comment]
closing out since latest version supports the mapping we have
