### ISSUE TITLE
virtualenvwrapper and fpp

### ISSUE THREAD

**Issue by slackorama** [facebook/PathPicker#199]
This may be more of a problem with virtualenvwrapper than with fpp but when I run it within a virtualenv, I get this error:

     /home/slack/.virtualenvs/pathpicker/bin/python: No module named virtualenvwrapper
     virtualenvwrapper.sh: There was a problem running the initialization hooks. 

     If Python could not import the module virtualenvwrapper.hook_loader,
     check that virtualenvwrapper has been installed for
     VIRTUALENVWRAPPER_PYTHON=/home/slack/.virtualenvs/pathpicker/bin/python and that PATH is
     set properly.

It seems `zsh -i` and virtualenvwrapper don't play nicely together.  Have you seen this behavior?

**Comment by pcottle** [comment]
Hrm never seen that before, but yeah it looks like it cant even start up python tbh. 

we just use the python command:
https://github.com/facebook/PathPicker/blob/master/fpp#L23

can you try a simple script instead that opens up python and executes hello world or something?

**Comment by pcottle** [comment]
closing out as I think this is mainly a virtualenv thing, but curious to hear back

**Comment by slackorama** [comment]
Yeah, same thing with a script that just has `echo "HI"` in it. 

    (conch)
    me@slackorama~/tmp
    ; echo 'echo "HI"; exit 0;' > test.sh
    (conch)
    me@slackorama~/tmp
    ; zsh -i test.sh                     
    /home/slack/.virtualenvs/slackorama/bin/python: No module named virtualenvwrapper
    virtualenvwrapper.sh: There was a problem running the initialization hooks. 
    
    If Python could not import the module virtualenvwrapper.hook_loader,
    check that virtualenvwrapper has been installed for
    VIRTUALENVWRAPPER_PYTHON=/home/slack/.virtualenvs/conch/bin/python and that PATH is
    set properly.
    HI

Well, looks like it's time for some yak shaving.

**Comment by pcottle** [comment]
Yeah thats a total yak shaving moment. Good luck doing down the rabbit hole!
