### ISSUE TITLE
PathFinder doesn't recognise pathes with spaces, tilde or parenthesis

### ISSUE THREAD

**Issue by keneanung** [facebook/PathPicker#200]
I have a git repository with files that include spaces and/or parenthesis in the file names. Those files don't get recognised. When using --nfc, only parts of the files are selectable. The same goes for backup files of gedit, which gain a tilde at the end (sample.txt~)

**Comment by pcottle** [comment]
@keneanung can you attach the input you are piping into `fpp` and the directory structure you are using? and where you are running it from?

Running with `--nfc` turns off a lot of our filesystem validation, so thats why partial matches and such show up (since its all guesswork)

**Comment by keneanung** [comment]
This is my current output of `git status` of the git repository https://github.com/svof/svof

fpp has issues with the umlaut `ä` (minor issue, not part of this actually), but it also won't recognise the `svo (install the zip, not me).xml` file for example. The files that end with the tilde won't be recognised either (they are backup files of gedit)
~~~
$ git status
Auf Branch UploadReleaseToAutoupdate
Ihr Branch ist auf dem selben Stand wie 'keneanung/UploadReleaseToAutoupdate'.
Änderungen, die nicht zum Commit vorgemerkt sind:
  (benutzen Sie "git add <Datei>...", um die Änderungen zum Commit vorzumerken)
  (benutzen Sie "git checkout -- <Datei>...", um die Änderungen im Arbeitsverzeichnis zu verwerfen)

	geändert:       doc/conf.py
	geändert:       svo (install the zip, not me).xml
	geändert:       svo template/config.lua

Unbeobachtete Dateien:
  (benutzen Sie "git add <Datei>...", um die Änderungen zum Commit vorzumerken)

	.travis.yml~
	classlist.lua~
	doc/enchanter.rst~
	doc/index.rst~
	dofree_deleayed.txt
	generate.lua~
	machineAccount
	machineAccount~
	out
	output.txt
	own svo/ndb-help.lua
	password
	password~
	precommit.lua~
	raw-svo.controllers.lua~
	raw-svo.defs.lua~
	raw-svo.dict.lua~
	raw-svo.dor.lua~
	raw-svo.metalimbcounter.lua~
	raw-svo.misc.lua~
	raw-svo.monklimbcounter.lua~
	raw-svo.serverside.lua~
	raw-svo.setup.lua~
	raw-svo.skeleton.lua~
	svo (enchanter).xml~
	travis.sh~

keine Änderungen zum Commit vorgemerkt (benutzen Sie "git add" und/oder "git commit -a")
~~~

**Comment by pcottle** [comment]
Ah yeah, I'm certain this is just because our file extensions dont have ~ as an option and the spaces regex doesnt allow commas. I think I can probably open up the regexes though and not break our backwards compatibility, let me draft this up when I have free time next (Wednesday)

**Comment by pcottle** [comment]
Alright threw this up! thanks to test coverage I can pretty confidently merge this :tada: 
no umlaut support yet, thats a utf8 thing with python2.7 that slows us down there :(
