### ISSUE TITLE
TypeError: can't concat bytes to str

### ISSUE THREAD

**Issue by nvictor** [facebook/PathPicker#201]
Hi there,

Really cool project. Installed it with Homebrew (OS X 10.10.5)  and got this error:

```
Traceback (most recent call last):
  File "/opt/boxen/homebrew/Cellar/fpp/0.6.2/libexec/src/processInput.py", line 15, in <module>
    import parse
  File "/opt/boxen/homebrew/Cellar/fpp/0.6.2/libexec/src/parse.py", line 162, in <module>
    PREPEND_PATH = getRepoPath().strip() + '/'
TypeError: can't concat bytes to str
```

Well I went into that file and put `str()` around `getRepoPath().strip()`. Seems to enable `fpp` to run.

Is it due to having Python 3?

**Comment by pcottle** [comment]
Ah yeah I'm sure thats the issue -- we support python 3 and run the tests in python3, but it doesnt cover 100% of the use cases.

@nvictor do you mind throwing up the PR for that? Ill happily merge it ASAP :)
