### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by kiranps** [facebook/PathPicker#207]
i would like to open multiple files in buffers instead of vertical splits in vim. is there any way to do that

**Comment by pcottle** [comment]
What would the command formatting be? right now we default to `vim -O $files`. you want to drop the `-O`?

we can make an env variable for this

**Comment by kiranps** [comment]
@pcottle i like vertical spits when there is only 2 file. opening more than 2 file in splits looks ugly

**Comment by ptzz** [comment]
+1

**Comment by pcottle** [comment]
on the way!
