### ISSUE TITLE
It would be great to include fish within the supported shells

### ISSUE THREAD

**Issue by hyiltiz** [facebook/PathPicker#209]
a feature request

**Comment by kevinastone** [comment]
:+1:

**Comment by pcottle** [comment]
Do you mean just in the README? theres some progress over on 205 in terms of potentially removing one of the conditions from the bash script, but we wont likely be able to run `fish`-y commands with fpp anytime soon.

But if you just mean in the README it'd be quite easy! Would have accepted the PR for that

**Comment by kevinastone** [comment]
#205 fixed my issue running `fpp` under fish.

**Comment by pcottle** [comment]
Sweet. I just made a new release and uploaded to `brew` so ill update the readme

**Comment by kevinastone** [comment]
:ok_hand:
