### ISSUE TITLE
Bad brew instructions

### ISSUE THREAD

**Issue by callumlocke** [facebook/PathPicker#21]
This:

```
brew upgrade; brew install fpp; fpp
```

Should probably be this:

```
brew update; brew install fpp; fpp
```

**Comment by pcottle** [comment]
Totally correct @callumlocke! My bad, trying to keep up with all the incoming issues / PR's. Thanks! should be reflected on the site now

**Comment by callumlocke** [comment]
you're doing a good job :+1:
