### ISSUE TITLE
Feature Request: option to output all found paths skipping the selection tool

### ISSUE THREAD

**Issue by maikelmeyers** [facebook/PathPicker#217]
Hi,

I would like to ask if it is possible to implement a new option that enables fpp to only output the found paths via stdout skipping the selection tool. This way it could be used as an input filter for fzf (https://github.com/junegunn/fzf)

Regards,
Maik

**Comment by pcottle** [comment]
Hey @maikelmeyers,

Can you describe your use case more? Fzf already allows selecting arbitrary input so I'm curious what the filter step on fpp would be used for.

Historically we've tried to stay away from the fzf workflow since they do such a better job at it :)

**Comment by maikelmeyers** [comment]
fzf does not know what a file path is. It can not filter out the file paths from the input by itself. Ideally it would need a pre- and a post filter. The pre-filter filters all lines from the input which contain a file path (i.e. grep output). This filtered output is piped into fzf. With fzf you select the lines with the files you want to process in some way. After pressing Enter this selected lines go into the post-filter. This one filters now the concrete file paths and send it to the $EDITOR or other command. In principle it is the same as fpp already does, but with fzf as the selection tool. Maybe it would be a better idea to have an option that enables to select fzf as internal selection tool.
I could do this filters with sed and/or awk or whatever, but fpp does already a good job at this, so why reinventing the wheel :)

**Comment by pcottle** [comment]
> the pre-filter filters all lines from the input which contain a file path (i.e. grep output).

would it simply output the lines that have a filepath match (as they came in) or would it output specifically the path in isolation? like say for:

```
asd dsa ~/real/path/to/file.py
# output this?
asd dsa ~/real/path/to/file.py
# or this?
/home/pcottle/real/path/to/file.py
```

this might be easy to do depending on the workflow, but i think integrating `fzf` as the selector would be quite difficult :-/

**Comment by maikelmeyers** [comment]
Sorry for bothering you. I now wrote a small bash wrapper script around fzf, which does nearly the same as fpp, at least for file paths and web urls.

**Comment by pcottle** [comment]
No worries -- helpful to hear your use case anyways :) glad you got unblocked!

**Comment by pcottle** [comment]
and yeah with the "command" argument you can pass to `fpp`, you can wrap it easily in custom functionality
