### ISSUE TITLE
Command mode not working with fish

### ISSUE THREAD

**Issue by uri** [facebook/PathPicker#226]
To reproduce

```
git status | fpp
F
c
ls
<return>
```

This produces the following error

```
Missing end to balance this if statement
~/.fpp/.fpp.sh (line 3): if type shopt > /dev/null; then
                         ^
fish: Error while reading file /Users/uri/.fpp/.fpp.sh
```

My `$SHELL` env var is set to `/usr/local/bin/fish`

#### versions

- fish: `fish, version 2.2.0`
- fpp: `fpp version 0.7.0`

**Comment by pcottle** [comment]
Can you try adding some fish detection to this line:
https://github.com/facebook/PathPicker/blob/master/src/output.py#L173

? Seems like zsh doesnt mind that block, but fish does

**Comment by uri** [comment]
Yeah removing the call to `appendToFile` fixes the problem.

**Comment by petr-tik** [comment]
is this closed then?

**Comment by pcottle** [comment]
I think so! Sorry for not updating sooner
