### ISSUE TITLE
Allow making non-interactive the default

### ISSUE THREAD

**Issue by scottjacobsen** [facebook/PathPicker#235]
My interactive shell startup is not fast. I would love it if there was a way to make non-interactive the default. How about an env var like `FPP_NONINTERACTIVE=true`?

**Comment by pcottle** [comment]
You'd also lose all aliases as well. Are you ok with that?

**Comment by scottjacobsen** [comment]
Yes, not a problem.

**Comment by pcottle** [comment]
Ok cool! We can add this to the ever-growing list of random environment variables that tweak functionality :P

Do you want to send the PR or should I? Should be fairly easy to whip up

**Comment by scottjacobsen** [comment]
If you want to point me in the right direction I'm happy to give it a
go.

Running

ag -i 'non.*interactive'

was not enlightening. I can see where the option is parsed, but not
where it is used.

**Comment by pcottle** [comment]
https://github.com/facebook/PathPicker/blob/master/src/output.py#L88 is a good example, as well as
https://github.com/facebook/PathPicker/blob/master/src/output.py#L120

you probably want to modify this logic:
https://github.com/facebook/PathPicker/blob/master/src/output.py#L173

lemme know if you have other q's!

**Comment by pcottle** [comment]
bit stale, closing this out
