### ISSUE TITLE
Selected text barely visible with some color schemes

### ISSUE THREAD

**Issue by ptzz** [facebook/PathPicker#236]
With some color schemes, the text of the selected item is barely visible. Could possibly be fixed by having fpp use ansi color "bright white" instead of "normal white" for the selected text. Not sure that's the best solution though.

FYI my terminal color scheme is the iTerm recommended config at https://github.com/w0ng/vim-hybrid.

**Comment by pcottle** [comment]
Can you attach a picture? id be open to changing it, curious how much better it looks

**Comment by ptzz** [comment]
Here you go:

![untitled](https://cloud.githubusercontent.com/assets/11414930/17651370/243d552a-6266-11e6-8222-7dbfd76bdeae.png)

In the iTerm color config it's clear that using "bright white" would fix the problem in this case:

![untitled2](https://cloud.githubusercontent.com/assets/11414930/17651388/798c7c04-6266-11e6-82e7-6a642dd8271c.png)

My current workaround is to increase the "Minimum contrast" setting in iTerm, which works well. Didn't have any issues with other application though, and have been using this color scheme for a couple of years.

**Comment by pcottle** [comment]
Hrm, so we use the curses API to do all of our screen printing and `curses` only has these colors:

```

        COLOR_BLACK   0
        COLOR_RED     1
        COLOR_GREEN   2
        COLOR_YELLOW  3
        COLOR_BLUE    4
        COLOR_MAGENTA 5
        COLOR_CYAN    6
        COLOR_WHITE   7
```

but we can change the rgb values of a given color. can you provide the rgb for bright white?

**Comment by ptzz** [comment]
RGB for ANSI "Bright White" would depend on the color scheme, but using "as white as possible" (R=G=B=255) it looks like this:

![untitled3](https://cloud.githubusercontent.com/assets/11414930/17652011/a62bc006-6272-11e6-9277-d7a164a9065b.png)

There seems to be a way to access the current terminal palette, from http://stackoverflow.com/questions/18551558/how-to-use-terminal-color-palette-with-curses:

> Passing the number -1 as color falls back to the default background and foreground colors

Guess this could be used to get the same text color as normal text (might not be white though).

> colors pairs 1-16 are the terminal color palette

Looks like bright white for the current color scheme is color pair 8.

Another option might be to use the `A_BOLD` or `A_REVERSE` curses color properties (looking at https://docs.python.org/2/howto/curses.html, haven't done any curses stuff myself)

Not sure which of these options are the best guarantee for a minimum contrast across all systems, color schemes and terminals... If the fpp selection background is fixed to blue, then bright white for the text is probably a good option as the default terminal text could potentially be blue. Hardcoding RGB to "maximum white" might be too outstanding in case of a low-contrast color scheme.

**Comment by ptzz** [comment]
> If the fpp selection background is fixed to blue, then bright white for the text is probably a good option

Looks like this can be achieved by the following change:
![untitled](https://cloud.githubusercontent.com/assets/11414930/17676671/df666e08-632f-11e6-8d24-14160971a44e.png)

(I never understood why ANSI treats bold and bright as the same thing. Code 0 is [Bold or increased intensity](https://en.wikipedia.org/wiki/ANSI_escape_code) )

**Comment by pcottle** [comment]
sorry this sat in my queue for a while! had some PTO. 

> Hardcoding RGB to "maximum white" might be too outstanding in case of a low-contrast color scheme.

so you think we shouldnt change the RGB for the default white we use? 

are you looking to increase contrast across all the text that is displayed or simply the current selection?

**Comment by ptzz** [comment]
I think RGB for default white can stay as is. And only change from default white to bold/bright white when the text is selected.

I think the snippet in my last post should do the trick once bold/bright i

**Comment by pcottle** [comment]
youre right after testing this out it is much better! just shipped the change and re-generated all the tests with attribute mapping 🎉

**Comment by ptzz** [comment]
Great! Does it makes sense to add bright attribute to the two other cases as well (`self.hovered and self.selected` and `self.selected`)? This is how it looks for those cases now:

![untitled](https://cloud.githubusercontent.com/assets/11414930/18041257/1fefeeae-6db7-11e6-948d-bc3eff5291cb.png)
