### ISSUE TITLE
Hangs when navigating to item

### ISSUE THREAD

**Issue by ptzz** [facebook/PathPicker#237]
The python process hangs when I try to navigate to an item where the complete path is not visible due to the window size.

Repro (with iTerm2, OSX 10.11.6):

* `ls -lah | fpp`
* Resize window so that the full path of some item does not fit inside the new window size
* Try to navigate to this item
--> fpp becomes unresponsive

**Comment by pcottle** [comment]
Can you attach your `fpp` version? We had an issue with an exception getting thrown in some of the older versions that prevented navigation

**Comment by ptzz** [comment]
0.7.1 fresh install with Homebrew. Tried with HEAD as well, same problem.

**Comment by pcottle** [comment]
worked fine for me in normal terminal:

![screenshot 2016-08-14 at 12 30 13 pm](https://cloud.githubusercontent.com/assets/1135007/17651378/dfcc8014-621a-11e6-90a7-82ea1e124da8.png)

let me try iterm

**Comment by pcottle** [comment]
yeah worked again :-/

![screenshot 2016-08-14 at 12 31 30 pm](https://cloud.githubusercontent.com/assets/1135007/17651390/0bde18de-621b-11e6-8dbc-b1cf87bc7a2c.png)

does entering command mode work perhaps? if you control-c when it hangs, do you get a stack?

**Comment by ptzz** [comment]
Odd. Entering commands does not work and there is no stack trace on ctrl-c. CPU is 100% for the fpp process (executing choose.py).

Seems it only occurs with `-a` flag to `ls`. A minimal repro for me is:

```
mkdir tmp2
cd tmp2
~/tmp2$ touch aaaaaaaa.py
~/tmp2$ touch aaaaaaaa2.py
~/tmp2$ /bin/ls -l | fpp
```
Still fine for you?

**Comment by pcottle** [comment]
oh nowwwww i can repro. im guessing this has to do with the amount of prepended text in the match lines. let me try to investigate tmr during a normal workday

**Comment by pcottle** [comment]
alright got a call stack! its an infinite loop in `updateDecoratedMatch`:

Traceback (most recent call last):
  File "/Users/pcottle/Dropbox (Facebook)/wip/PathPicker/src/choose.py", line 100, in <module>
    curses.wrapper(lambda x: doProgram(x, flags))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "/Users/pcottle/Dropbox (Facebook)/wip/PathPicker/src/choose.py", line 100, in <lambda>
    curses.wrapper(lambda x: doProgram(x, flags))
  File "/Users/pcottle/Dropbox (Facebook)/wip/PathPicker/src/choose.py", line 42, in doProgram
    screen.control()
  File "/Users/pcottle/Dropbox (Facebook)/wip/PathPicker/src/screenControl.py", line 362, in control
    self.processDirty()
  File "/Users/pcottle/Dropbox (Facebook)/wip/PathPicker/src/screenControl.py", line 602, in processDirty
    self.lineObjs[index].output(self.colorPrinter)
  File "/Users/pcottle/Dropbox (Facebook)/wip/PathPicker/src/format.py", line 269, in output
    self.updateDecoratedMatch(maxLen=spaceForPrinting)
  File "/Users/pcottle/Dropbox (Facebook)/wip/PathPicker/src/format.py", line 231, in updateDecoratedMatch

**Comment by pcottle** [comment]
Woohoo!! Fixed the bug and added test coverage 🎉 🎉 🎉 . Thanks again for the bug report @ptzz and insisting that there was an issue when i couldnt repro at first :P

turns out it was a pretty brutal but easy to make mistake around forgetting to take into account the prepended text when figuring out the max length. most inputs dont have long prepends which is why it wasnt easy to repro at first

**Comment by ptzz** [comment]
Good to hear! 👍
