### ISSUE TITLE
Prevent sourcing .bashrc/.zshrc

### ISSUE THREAD

**Issue by Granitas** [facebook/PathPicker#238]
Every time fpp is called it sources .zshrc. Why? 

I have quite heavy rc files and it renders fpp complete unusable, not to mention the fact it also prints all of the fortunes or whatever you have in your shell's rc.

**Comment by pcottle** [comment]
Lets merge into #235 . I gave a few links to code in there if you want to take a stab at putting up the PR :)

I agree that some bashrcs can be quite heavy, but when most people used command mode they assumed their aliases would work. so we developed for that scenario
