### ISSUE TITLE
typo in code (TypeError: 'builtin_function_or_method' object is not subscriptable)

### ISSUE THREAD

**Issue by pszynk** [facebook/PathPicker#242]
Hey, found a [typo](https://github.com/facebook/PathPicker/blob/cd2855934bb450b9e7df2a08127cc6ab549e5507/src/output.py#L206) in your code. Wrong brackets in method `appendExit` in file `output.py` you have  `shell.endswith['rc']`, obviously should be `shell.endswith('rc')`

**Comment by pcottle** [comment]
You're totally right -- gah. It's hard to get test coverage in this area since it relates to the actual bash execution.

will fix in a moment, thanks for the report!
