### ISSUE TITLE
Why relative paths prepended with 'home' are converted into absolute paths?

### ISSUE THREAD

**Issue by iamFIREcracker** [facebook/PathPicker#243]
I have a repository with a top level 'home' directory but when I run `git status | fpp` none of the changed files contained in that directory are picked by fpp.

When I ignore file system checks (ie. `git status | fpp -nfc`) and select one of those files from that directory, the editor loads up an empty buffer because fpp prepends a slash to the selected path (ie. I select `home/.vimrc` and the editor tries to open `/home/.vimrc`).

What edge case is fpp trying to catch here?

It doesn't seem like a bug though, because the behavior has been documented in the parse module (https://github.com/facebook/PathPicker/blob/master/src/parse.py#L310), and there is even a unit test for it..

**Comment by pcottle** [comment]
Ah yes, this is leftover from when FPP was developed internally at Facebook. We have some code search / grepping tools that return paths that are absolute but without the preceding slash, and all of our repos are mounted off of our homedir like:

```
[pcottle:~/www:(changeFoo)]$ pwd
/home/pcottle/www
```

hence, thats why the hack is there. we have a few thousand users internally so im hesitant to remove it, but you could just drop those two lines from your local version if you want.

or we could add yet another env variable that turns it off :P
