### ISSUE TITLE
git clone link is wrong in the readme file

### ISSUE THREAD

**Issue by nizamsp** [facebook/PathPicker#248]
git clone git@github.com:facebook/PathPicker.git
Cloning into 'PathPicker'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

It should be
git clone https://github.com/facebook/PathPicker.git

**Comment by pcottle** [comment]
Good catch! I must have been lazy and just copied the shortcut that renders for me. thx for the issue -- must have been incorrect for years :O

**Comment by nizamsp** [comment]
Thank you! I was also wondering how come a 3021 star rated repo had this bug. I think you have reached only half of the potential users :)
The clone link would have worked for you since you own the repo.

**Comment by pcottle** [comment]
Yeah, that's why its an easy mistake to make. Tested it "myself" but not a good test plan clearly
