### ISSUE TITLE
[c] enter command mode doesn't work after using [A] toggle

### ISSUE THREAD

**Issue by mellowcandle** [facebook/PathPicker#249]
After Toggling the entire files using [A]
[c] enter command mode  stops working.

Detected on Arch Linux (Bash)

**Comment by pcottle** [comment]
can you give me a repro of the input you got where this happened? how many files are we talking?

I think if you pipe in 1,000 files it might just hang for a while but im not sure

**Comment by mellowcandle** [comment]
Easily reproducable: 184 files for instance:

find . -name *.c | fpp

find output:

./tests/tests.c
./arch/x86/kernel/cpu.c
./arch/x86/kernel/ioapic.c
./arch/x86/kernel/apic.c
./arch/x86/kernel/gdt.c
./arch/x86/kernel/idt.c
./drivers/timer/i8254.c
./drivers/input/kbd.c
./drivers/acpi/acpica/rsinfo.c
./drivers/acpi/acpica/psxface.c
./drivers/acpi/acpica/evmisc.c
./drivers/acpi/acpica/nseval.c
./drivers/acpi/acpica/hwsleep.c
./drivers/acpi/acpica/nsprepkg.c
./drivers/acpi/acpica/nsaccess.c
./drivers/acpi/acpica/tbutils.c
./drivers/acpi/acpica/uteval.c
./drivers/acpi/acpica/psscope.c
./drivers/acpi/acpica/dsinit.c
./drivers/acpi/acpica/nswalk.c
./drivers/acpi/acpica/utxferror.c
./drivers/acpi/acpica/utascii.c
./drivers/acpi/acpica/tbinstal.c
./drivers/acpi/acpica/utprint.c
./drivers/acpi/acpica/evevent.c
./drivers/acpi/acpica/dsdebug.c
./drivers/acpi/acpica/psloop.c
./drivers/acpi/acpica/utstrtoul64.c
./drivers/acpi/acpica/utaddress.c
./drivers/acpi/acpica/evgpeutil.c
./drivers/acpi/acpica/dsobject.c
./drivers/acpi/acpica/exregion.c
./drivers/acpi/acpica/nsload.c
./drivers/acpi/acpica/utnonansi.c
./drivers/acpi/acpica/utxfinit.c
./drivers/acpi/acpica/evxface.c
./drivers/acpi/acpica/exconvrt.c
./drivers/acpi/acpica/hwtimer.c
./drivers/acpi/acpica/utdebug.c
./drivers/acpi/acpica/exoparg1.c
./drivers/acpi/acpica/utexcep.c
./drivers/acpi/acpica/nsxfobj.c
./drivers/acpi/acpica/hwgpe.c
./drivers/acpi/acpica/utcopy.c
./drivers/acpi/acpica/utclib.c
./drivers/acpi/acpica/utglobal.c
./drivers/acpi/acpica/nsrepair2.c
./drivers/acpi/acpica/exstore.c
./drivers/acpi/acpica/utmisc.c
./drivers/acpi/acpica/nsinit.c
./drivers/acpi/acpica/dsfield.c
./drivers/acpi/acpica/nsalloc.c
./drivers/acpi/acpica/exmutex.c
./drivers/acpi/acpica/rsdumpinfo.c
./drivers/acpi/acpica/psopinfo.c
./drivers/acpi/acpica/exfield.c
./drivers/acpi/acpica/nsutils.c
./drivers/acpi/acpica/evregion.c
./drivers/acpi/acpica/psutils.c
./drivers/acpi/acpica/utalloc.c
./drivers/acpi/acpica/uterror.c
./drivers/acpi/acpica/tbdata.c
./drivers/acpi/acpica/exoparg6.c
./drivers/acpi/acpica/rsmemory.c
./drivers/acpi/acpica/hwpci.c
./drivers/acpi/acpica/rscalc.c
./drivers/acpi/acpica/utobject.c
./drivers/acpi/acpica/epos_hal.c
./drivers/acpi/acpica/exprep.c
./drivers/acpi/acpica/utosi.c
./drivers/acpi/acpica/nsxfname.c
./drivers/acpi/acpica/hwvalid.c
./drivers/acpi/acpica/exstorob.c
./drivers/acpi/acpica/evrgnini.c
./drivers/acpi/acpica/exfldio.c
./drivers/acpi/acpica/dsutils.c
./drivers/acpi/acpica/utmutex.c
./drivers/acpi/acpica/utpredef.c
./drivers/acpi/acpica/dswload2.c
./drivers/acpi/acpica/tbfind.c
./drivers/acpi/acpica/exoparg3.c
./drivers/acpi/acpica/utlock.c
./drivers/acpi/acpica/exresolv.c
./drivers/acpi/acpica/nsarguments.c
./drivers/acpi/acpica/exmisc.c
./drivers/acpi/acpica/evxfgpe.c
./drivers/acpi/acpica/nsparse.c
./drivers/acpi/acpica/exresnte.c
./drivers/acpi/acpica/tbxface.c
./drivers/acpi/acpica/exutils.c
./drivers/acpi/acpica/nsobject.c
./drivers/acpi/acpica/utstate.c
./drivers/acpi/acpica/rsio.c
./drivers/acpi/acpica/utinit.c
./drivers/acpi/acpica/hwxfsleep.c
./drivers/acpi/acpica/hwxface.c
./drivers/acpi/acpica/hwregs.c
./drivers/acpi/acpica/dswscope.c
./drivers/acpi/acpica/utxface.c
./drivers/acpi/acpica/hwesleep.c
./drivers/acpi/acpica/dsmethod.c
./drivers/acpi/acpica/evglock.c
./drivers/acpi/acpica/tbprint.c
./drivers/acpi/acpica/dsargs.c
./drivers/acpi/acpica/utxfmutex.c
./drivers/acpi/acpica/utuuid.c
./drivers/acpi/acpica/rslist.c
./drivers/acpi/acpica/nsdump.c
./drivers/acpi/acpica/nsconvert.c
./drivers/acpi/acpica/dsmthdat.c
./drivers/acpi/acpica/exstoren.c
./drivers/acpi/acpica/dswstate.c
./drivers/acpi/acpica/evgpe.c
./drivers/acpi/acpica/pstree.c
./drivers/acpi/acpica/rsmisc.c
./drivers/acpi/acpica/exdebug.c
./drivers/acpi/acpica/hwacpi.c
./drivers/acpi/acpica/nspredef.c
./drivers/acpi/acpica/evhandler.c
./drivers/acpi/acpica/tbfadt.c
./drivers/acpi/acpica/utresrc.c
./drivers/acpi/acpica/evgpeinit.c
./drivers/acpi/acpica/rsirq.c
./drivers/acpi/acpica/nsxfeval.c
./drivers/acpi/acpica/evsci.c
./drivers/acpi/acpica/nsrepair.c
./drivers/acpi/acpica/utids.c
./drivers/acpi/acpica/pswalk.c
./drivers/acpi/acpica/excreate.c
./drivers/acpi/acpica/tbxfload.c
./drivers/acpi/acpica/nsnames.c
./drivers/acpi/acpica/exconcat.c
./drivers/acpi/acpica/utdecode.c
./drivers/acpi/acpica/dscontrol.c
./drivers/acpi/acpica/tbxfroot.c
./drivers/acpi/acpica/utmath.c
./drivers/acpi/acpica/rsaddr.c
./drivers/acpi/acpica/dswexec.c
./drivers/acpi/acpica/utownerid.c
./drivers/acpi/acpica/evgpeblk.c
./drivers/acpi/acpica/evxfevnt.c
./drivers/acpi/acpica/dswload.c
./drivers/acpi/acpica/psopcode.c
./drivers/acpi/acpica/rscreate.c
./drivers/acpi/acpica/rsutils.c
./drivers/acpi/acpica/evxfregn.c
./drivers/acpi/acpica/exsystem.c
./drivers/acpi/acpica/utbuffer.c
./drivers/acpi/acpica/exconfig.c
./drivers/acpi/acpica/rsserial.c
./drivers/acpi/acpica/uthex.c
./drivers/acpi/acpica/rsxface.c
./drivers/acpi/acpica/extrace.c
./drivers/acpi/acpica/psobject.c
./drivers/acpi/acpica/psargs.c
./drivers/acpi/acpica/exdump.c
./drivers/acpi/acpica/utcache.c
./drivers/acpi/acpica/dsopcode.c
./drivers/acpi/acpica/nsdumpdv.c
./drivers/acpi/acpica/exresop.c
./drivers/acpi/acpica/utstring.c
./drivers/acpi/acpica/uttrack.c
./drivers/acpi/acpica/psparse.c
./drivers/acpi/acpica/exnames.c
./drivers/acpi/acpica/utdelete.c
./drivers/acpi/acpica/exoparg2.c
./drivers/acpi/acpica/nssearch.c
./drivers/acpi/acpi.c
./drivers/video/VIDEO_textmode.c
./drivers/serial/serial.c
./kernel/ticks.c
./kernel/interrupts.c
./kernel/kernel.c
./kernel/panic.c
./kernel/mmodules.c
./lib/string.c
./lib/elf.c
./lib/printk.c
./lib/ctype.c
./lib/kmalloc.c
./mem/kheap.c
./mem/virtual.c
./mem/physical.c
./modules/program.c

**Comment by pcottle** [comment]
Ah yeah, I can repro. its likely due to the fact that it tries to render the selection and it goes off screen

justasec

**Comment by pcottle** [comment]
Fixed! 🎉  and with some test coverage -- sorry this was clowny, I should have anticipated hundreds (or really just more than the screen height) of files would get added
