### ISSUE TITLE
Doesn't handle paths with spaces in them

### ISSUE THREAD

**Issue by frou** [facebook/PathPicker#25]
Both the highlighting and file-opening are tripped up by paths with spaces in them.

I tested with the output of OS X's `mdfind -name foo` (one path per line) piped into fpp.

**Comment by zkanda** [comment]
I can confirm this issue,
![screen shot 2015-05-08 at 11 33 35 am](https://cloud.githubusercontent.com/assets/5354184/7530155/1580e9e2-f576-11e4-9f20-3dd629f602f0.png)

**Comment by idf** [comment]
+1 for this issue.

**Comment by mrjbq7** [comment]
+1

**Comment by pcottle** [comment]
Lets merge this into #83, since we'll have to go to the filesystem to validate build this
