### ISSUE TITLE
URL for debian package

### ISSUE THREAD

**Issue by Boruch-Baum** [facebook/PathPicker#255]
I was directed from the Facebook PathPicker URL to https://github.com/facebook/PathPicker/releases/tag/0.7.1 in order to get the deb package, but it isn't there, and the source tarballs that are there don't include a make file.

**Comment by pcottle** [comment]
hrm @Boruch-Baum what do you mean? Forgive me but i have zero experience with *nix distributions, its all been written by external contributors.

the tar file is there for me. for debian we have a separate script that makes the release

**Comment by poros** [comment]
It would be great if you could add the debian package created via the script with the files you provide for each release. This would avoid people to need to figure out how to properly run the script since there is no documentation about how to do it (e.g. you need to run it from a specific folder)

**Comment by pcottle** [comment]
The problem is that I can't quite generate the debian package myself on my machine :-/ would adding to the README help? If you send me some content I can put it in there

**Comment by poros** [comment]
The steps I did to generate the debian package were just:
```bash
$ git clone https://github.com/facebook/PathPicker.git
$ cd debian
$ ./package.sh 
$ ls ../fpp_0.7.2_noarch.deb
```

**Comment by pcottle** [comment]
Should be updated now! thx :)
