### ISSUE TITLE
Long paths are prefixed with three dots

### ISSUE THREAD

**Issue by hegazy** [facebook/PathPicker#257]
When I run `git diff HEAD~1 --stat`
I get the full relative paths on the output (9 levels down)
but when I pipe it to fpp I got them prefixed with three dots.

**Comment by pcottle** [comment]
Can you attach a screenshot? We often "shorten" the path with three dots so the full thing can be displayed in the terminal, and we assume the end of the path is more important than the front

**Comment by devisnik** [comment]
@hegazy Did you see #167 ?

**Comment by hegazy** [comment]
@pcottle It's the same issue @devisnik mentioned I guess as I can't open the file itself as it's opening the path prefixed with those three dots
![screenshot from 2017-01-12 12-34-53](https://cloud.githubusercontent.com/assets/2749269/21886341/fa448372-d8c3-11e6-9867-e2495ff1067a.png)

**Comment by devisnik** [comment]
Using `--numstat` instead of `--stat` with the git command works for me.

**Comment by hegazy** [comment]
@devisnik Works for me too! But why it's displaying the full qualified paths on standard output and converts it when getting piped?

**Comment by pcottle** [comment]
OOoh yeah, this is actually upstream of our code and we can't do anything. Git for whatever reason checks if its getting piped into a stdin and decides to (not-so-)helpfully shorten and prepend the paths, and then we can't open them

`--numstat` is the way to go. thanks @devisnik  for the fix

**Comment by hegazy** [comment]
We can also use the command like this `git show HEAD --stat=<width>` It seems that the default value is set to 80. We can override that by increasing `<width>`
