### ISSUE TITLE
Command fails when on OS X 10.12.4 when $SHELL isn't defined

### ISSUE THREAD

**Issue by hborders** [facebook/PathPicker#259]
I just installed `fpp` via `brew` onto OS X 10.12.4. I didn't have `$SHELL` defined. When I ran `git status | fpp`, selected some files, and used `git add ` for my command, I got the following error:

```
/usr/local/bin/fpp: line 53: /bin/false: No such file or directory
```

I looked on line 53, and it expected `$SHELL` to be defined. For some reason, if `$SHELL` and `$BASH` aren't defined `brew` or OS X defaults them to `/bin/false` (which doesn't even exist, `false` is `/usr/bin/false` on OS X).

This isn't necessarily your problem, but maybe `fpp` could at a minimum verify that the `$SHELL` file exists before trying to run commands against it?

**Comment by pcottle** [comment]
What shell were you actually using? I'm on 10.12.3. We delegate to shell only if we think we are in a bash or zsh environment

can you check what `$BASH` or `$ZSH_NAME` were outputting?

**Comment by hborders** [comment]
> can you check what $BASH or $ZSH_NAME were outputting?

I `echo`-ed `$BASH` and `$SHELL` right before the `if`:

```
  echo "bash: $BASH, shell: $SHELL"
  if [ -n "$BASH" -o -n "$ZSH_NAME" ]; then
    $SHELL $IFLAG "$FPP_DIR/.fpp.sh" < /dev/tty
  else
    /bin/bash $IFLAG "$FPP_DIR/.fpp.sh" < /dev/tty
  fi
```

and got this output:

```
bash: /bin/bash, shell: /bin/false
```

Of course, if I `export SHELL=/usr/local/bin/bash` in my `.bashrc` everything works fine.

**Comment by pcottle** [comment]
yeah this is quite odd, we can add in a hack to fix this but i'm just deciding the best course of action.

should we check `$SHELL` exists and, if so, then call it? what if they fix shell to resolve to `/usr/bin/false`? then the check becomes true and we have the same problem.

should we perhaps instead just check explicitly for `$BASH` and call `$BASH` for that case, and then shell for ZSH name?

I'm leaning towards the latter but curious what you think.

**Comment by hborders** [comment]
I think you should prefer `$SHELL` if possible, and just handle this specific case. It really seems like an OS X bug to me. Thus, do something like:

```
if [ -n "$BASH" -o -n "$ZSH_NAME" ]; then
  if [ "${SHELL}" -ne "/bin/false" ]
    $SHELL $IFLAG "$FPP_DIR/.fpp.sh" < /dev/tty
  else
    $BASH $IFLAG "$FPP_DIR/.fpp.sh" < /dev/tty
  fi
else
  /bin/bash $IFLAG "$FPP_DIR/.fpp.sh" < /dev/tty
fi
```

**Comment by pcottle** [comment]
comparing exactly to `/bin/false` seems odd -- could we instead do a check that shell exists as a file/executable?

youll have to forgive me for asking but my bash is really weak, i always have to google "how to determine if file exists in bash"...

**Comment by hborders** [comment]
That makes sense. I'm just thinking since this is a hacky workaround, mitigation should be limited to mitigate possible side-effects.

It might even be good to emit a warning message to `stderr` saying they should `export SHELL` explicitly to work around this bug.

**Comment by pcottle** [comment]
```
[pcottle:~/Dropbox (Facebook)/wip/PathPicker:master]$ ./fpp
Using previous input piped to fpp...
nothing to do!
[pcottle:~/Dropbox (Facebook)/wip/PathPicker:master]$ SHELL='/bin/false'
[pcottle:~/Dropbox (Facebook)/wip/PathPicker:master]$ ./fpp
Using previous input piped to fpp...
Your SHELL bash variable /bin/false does not exist, please export it explicitly
nothing to do!
[pcottle:~/Dropbox (Facebook)/wip/PathPicker:master]$ SHELL='/bin/bash'
[pcottle:~/Dropbox (Facebook)/wip/PathPicker:master]$ ./fpp
Using previous input piped to fpp...
nothing to do!
```

alright should be fixed now! when installed off master

**Comment by hborders** [comment]
Nice! Thanks!

**Comment by pcottle** [comment]
No problem!
