### ISSUE TITLE
Crash when resizing screen to a smaller size

### ISSUE THREAD

**Issue by saveriomiroddi** [facebook/PathPicker#260]
I've found a bug in the screen resizing; I can reproduce it all the times on the test input, on revision 46cf45e, by:

- execute fpp on an input which is 2 or more pages long, with the terminal window fully extended (in my case, it's 190x52)
- scroll down to the second page
- resize to a smaller screen (in my case, I use Alt+F7, which resizes straight away to 80x19)
- kaboom!

Stack trace:

      File "/home/chicken/PathPicker/src/choose.py", line 100, in <module>
        curses.wrapper(lambda x: doProgram(x, flags))
      File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
        return func(stdscr, *args, **kwds)
      File "/home/chicken/PathPicker/src/choose.py", line 100, in <lambda>
        curses.wrapper(lambda x: doProgram(x, flags))
      File "/home/chicken/PathPicker/src/choose.py", line 42, in doProgram
        screen.control()
      File "/home/chicken/PathPicker/src/screenControl.py", line 363, in control
        self.moveCursor()
      File "/home/chicken/PathPicker/src/screenControl.py", line 671, in moveCursor
        self.stdscr.move(y, x)
    _curses.error: wmove() returned ERR

Input:

    chicken ccccccccccccccccccccccccccccccccccccccccc
    chicken: Saverio Miroddi <chicken@chicken.chicken>
    chicken: chicken chicken 00 00:00:00 0000 +666

        chicken `chicken`, chicken chicken chicken chicken chicken chicken, chicken chicken chicken/chicken/chicken

    D chicken/chicken
    D chicken/chicken.lock
    D chicken/chicken
    D chicken/README.md
    D chicken/chicken
    D chicken/chicken
    D chicken/chicken/chicken_chicken_chicken.sh
    D chicken/chicken/chicken-chicken
    D chicken/chicken/chicken_chicken_chicken.sh
    D chicken/chicken/chicken
    D chicken/chicken/README.md
    D chicken/chicken
    D chicken/chicken/chicken.rb
    D chicken/chicken/README.md
    D chicken/chicken/chicken/README.md
    D chicken/chicken/chicken/README.md
    D chicken/chicken/chicken/chicken/chicken.rb
    D chicken/chicken/chicken/chicken/chicken/chicken_chicken.chicken/chicken
    D chicken/chicken/chicken/chicken.rb
    D chicken/chicken/chicken/chicken/chicken.rb
    D chicken/chicken/chicken/chicken/chicken/chicken.chicken.erb
    D chicken/chicken/chicken/chicken/chicken.rb
    D chicken/chicken/chicken/chicken.rb
    D chicken/chicken/chicken/chicken/chicken.rb
    D chicken/chicken/chicken/chicken/chicken/chicken_chicken.chicken.erb
    D chicken/chicken/chicken/chicken/chicken/chicken/chicken
    D chicken/chicken/chicken/chicken/chicken/chicken/chicken
    D chicken/chicken/chicken/chicken/chicken/chicken.chicken.erb
    D chicken/chicken/chicken/chicken
    D chicken/chicken/chicken/chicken.lock
    D chicken/chicken/chicken/README.md
    D chicken/chicken/chicken/chicken/chicken.rb
    D chicken/chicken/chicken/chicken/chicken/chicken/chicken
    D chicken/chicken/chicken/chicken/chicken/chicken/chicken.cf
    D chicken/chicken/chicken/chicken/chicken/chicken.chicken/chicken
    D chicken/chicken/chicken/chicken/chicken/chicken/chicken
    D chicken/chicken/chicken/chicken/chicken/chicken/chicken-chicken
    D chicken/chicken/chicken/chicken/chicken/chicken/chicken-chicken.bak
    D chicken/chicken/chicken/chicken/chicken/chicken.chicken.local
    D chicken/chicken/chicken/chicken/chicken/chicken/chicken-chicken.conf
    D chicken/chicken/chicken/chicken/chicken/chicken/chicken-chicken.chicken.bak
    D chicken/chicken/chicken/chicken.rb
    D chicken/chicken/chicken/chicken/chicken.rb
    D chicken/chicken/chicken/chicken/chicken.rb
    D chicken/chicken/chicken/chicken/chicken.rb
    D chicken/chicken/chicken/chicken/chicken.rb
    D chicken/chicken/chicken/chicken/chicken/chicken/chicken.bak
    D chicken/chicken/chicken/chicken/chicken/chicken/chicken.erb
    D chicken/chicken/chicken/chicken/chicken/chicken.chicken.bak
    D chicken/chicken/chicken/chicken/chicken/chicken.chicken.erb
    D chicken/chicken/chicken/chicken/chicken/chicken/chicken.chicken.erb
    D chicken/chicken/chicken/chicken/chicken/chicken/chicken.chicken.erb
    D chicken/chicken/chicken/chicken/chicken/chicken/chicken.chicken.erb
    D chicken/chicken/chicken/chicken/chicken/chicken/chicken.chicken.erb
    D chicken/chicken/chicken/chicken/chicken/chicken/chicken/chicken_chicken_chicken.rb
    D chicken/chicken/chicken/chicken/chicken/chicken/chicken/chicken_chicken.rb
    D chicken/chicken/chicken/README.md
    D chicken/chicken/chicken/README.md
    D chicken/chicken/chicken/chicken/chicken/chicken.conf
    D chicken/chicken/chicken/chicken.rb
    D chicken/chicken/chicken/chicken/chicken.rb
    D chicken/chicken/chicken/README.md
    D chicken/chicken/chicken/chicken/chicken.rb
    D chicken/chicken/chicken/chicken/chicken/chicken/chicken.conf
    D chicken/chicken/chicken/chicken/chicken/chicken/chicken.chicken.bak
    D chicken/chicken/chicken/chicken/chicken/chicken
    D chicken/chicken/chicken/chicken/chicken/chicken.chicken/chicken
    D chicken/chicken/chicken/chicken/chicken/chicken.chicken/chicken
    D chicken/chicken/chicken/chicken/chicken/chicken/chicken_chicken.sh
    D chicken/chicken/chicken/chicken.rb
    D chicken/chicken/chicken/chicken/chicken.rb
    D chicken/chicken/chicken/chicken/chicken.rb
    D chicken/chicken/chicken/chicken/chicken.rb
    D chicken/chicken/chicken/chicken/chicken/chicken.chicken.erb
    D chicken/chicken/chicken/README.md
    D chicken/chicken/chicken/README.md
    D chicken/chicken/chicken/chicken/chicken.rb
    D chicken/chicken/chicken/chicken/chicken/chicken/chicken.chicken/chicken
    D chicken/chicken/chicken/chicken.rb
    D chicken/chicken/chicken/chicken/chicken.rb
    D chicken/chicken/chicken/chicken/chicken/chicken.chicken.chicken.chicken.bak
    D chicken/chicken/chicken/chicken/chicken/chicken.chicken.erb
    D chicken/chicken/chicken/chicken/chicken/chicken.chicken_chicken.chicken.erb
    D chicken/chicken/chicken/README.md
    D chicken/chicken/chicken/chicken/chicken.rb
    D chicken/chicken/chicken/chicken/chicken/chicken/chicken_chicken.rb
    D chicken/chicken/chicken/chicken/chicken_chicken_chicken_chicken_chicken.rb
    D chicken/chicken/chicken/chicken/chicken_chicken_chicken.rb
    D chicken/chicken/chicken/chicken.rb
    D chicken/chicken/chicken/chicken/chicken_chicken.rb
    D chicken/chicken/chicken/chicken/chicken.rb
    D chicken/chicken/chicken/chicken/chicken_chicken.rb
    D chicken/chicken/chicken/chicken/chicken.rb

**Comment by pcottle** [comment]
can you paste your `fpp --version`? we fixed a few things relating to screen sizes recently

**Comment by saveriomiroddi** [comment]
Revision https://github.com/facebook/PathPicker/commit/46cf45e170ec0cb147255c04c5c54d89e16d136c is v0.7.2.

**Comment by pcottle** [comment]
Ah yes I can repro, really has to get quite short height-wise to reproduce this :)

**Comment by pcottle** [comment]
Thanks for the report @saveriomiroddi ! Should be fixed now, was actually quite simple
