### ISSUE TITLE
make fpp default to process output of last command

### ISSUE THREAD

**Issue by ri-aje** [facebook/PathPicker#263]
can we default fpp (or some equivalent short form) to receive inputs from last command? i.e., if I just type fpp, I would like it to process outputs of my last command as if I have rerun my last command and piped to fpp. I found this pattern often occurs in my use, where I run a command that could dump many files (exactly how many I don't know before hand) and I examine the output and found something interesting and would like to take a closer look at some of these files. currently the only option is to bring up my last command and type |fpp and I would like to just type fpp to have an equivalent effect.

**Comment by oalders** [comment]
There was some discussion about this in #171

**Comment by ri-aje** [comment]
they are not about the same, right? #171 wants fpp assembled commands to enter some sort of history, whereas I want it to execute my last command (already in history) for me when invoked naked. put it in an example,

bash-prompt> my-last-command 
bash-prompt> fpp

and I want the fpp command executes as if I have typed "my-last-command | fpp" in its place. this should be easier to implement than #171. fpp only needs to check if it is sitting on a piped position and if not, then tail -1 ~/.bash_history and execute it for me then process its outputs.

**Comment by ri-aje** [comment]
on a second thought, maybe `history|tail -2|head -1` is better.

**Comment by pcottle** [comment]
Yeah the more appropriate thing here is to perhaps just use history + eval with something like:
`eval "$(fc -ln | tail -2 | head -1)" | fpp`

this worked for me, for example doing:
```
> ls -la
> eval "$(fc -ln | tail -2 | head -1)" | fpp
```
and I was able to get the ls output piped into fpp. with a short alias that might make for a nice solution

but I do think having it re-execute as the default behavior is a bit too aggressive, especially when the last command could have been something destructive!

thanks for dropping by with the feedback though
