### ISSUE TITLE
do not support 'll' or 'ls -l' command output soft link

### ISSUE THREAD

**Issue by zhanggang807** [facebook/PathPicker#264]
as title

**Comment by pcottle** [comment]
![screenshot 2017-08-23 at 10 00 43 am](https://user-images.githubusercontent.com/1135007/29628314-f0fb7a8e-87e9-11e7-8b3e-088d3f2deca1.png)

can you clarify? `ls -l | fpp` works fine for me

**Comment by zhanggang807** [comment]
![image](https://user-images.githubusercontent.com/4559603/29756425-76d6ab8e-8bd6-11e7-842e-991d9f8188b3.png)

if 'll' command output a soft link

**Comment by pcottle** [comment]
Ooooh i see what you mean. Yeah sadly we only support one match per line, it'd be a huge overhaul to support multiple matches in a given line. Sadly this is probably out of scope, but you could try splitting on '->' in this case and grabbing the first result before piping to fpp...

**Comment by zhanggang807** [comment]
Got it.
