### ISSUE TITLE
Fails to open vim if too many files selected

### ISSUE THREAD

**Issue by ptzz** [facebook/PathPicker#273]
With the default fpp options, vim sometimes fails to open due to excessive commandline. With FPP_DISABLE_SPLIT set it usually works, because line numbers are not passed for each file. Is there a way to detect this and retry vim without specifying line numbers for this case?

**Comment by pcottle** [comment]
Hrm, this feels more like a downstream issue than upstream solvable by fpp.

we could try to guess which editor you have and how many files they support, but that could get out of sync with the version of vim or plugins you have (and we would treat all of vim the same)

we could detect an error code and then try again but that'd have to be on the bash level, not inside python where the command formatting happens.

I don't see a super easy way of supporting this, but happy to review a PR or something more concrete! gonna close out in the meantime
