### ISSUE TITLE
Detecting filenames with "%"

### ISSUE THREAD

**Issue by NGenetzky** [facebook/PathPicker#276]
**Is there a way to change what is detected as a filepath?**

I am working with the Yocto Project and they use "%" in recipes. I am noticing that these are not detected by fpp as filepaths. 

```
## HEAD (no branch)
M  meta-vaddio/recipes-kernel/linux/linux-xlnx/vaddio-corvus.dts
UU meta-vaddio/recipes-kernel/linux/linux-xlnx_%.bbappend
?? .bash_history
?? meta-vaddio-util/recipes-vaddio/dev/hw-validation/
```

Please let me know if you would like additional content submitted in the issue.

**Comment by pcottle** [comment]
ahh yeah, I left that out somewhat intentionally

it should be somewhat feasible to add it to one of these regexes:
https://github.com/facebook/PathPicker/blob/master/src/parse.py#L16

you can see that `@`is included here:
https://github.com/facebook/PathPicker/blob/master/src/parse.py#L111

for retina files. try adding a slash there and run the unit tests and see what fails / succeeds :)

**Comment by NGenetzky** [comment]
I can understand the desire to keep the false matches to a minimal.

Any chance you would consider "%." as an acceptable match? Here are some other examples that people using yocto might have.
```
meta-vaddio/recipes-kernel/linux/linux-xlnx_%.bbappend
meta-vaddio/recipes-kernel/linux/linux-xlnx_3.%.bbappend
meta-vaddio/recipes-kernel/linux/linux-xlnx_3.1%.bbappend
```

**Comment by pcottle** [comment]
Yep that could work, does it always end in percent and then a period? That would help scale down the regex changes.

**Comment by pcottle** [comment]
Sorry for the repetitive email reply -- i added support for this just now! Should be good to go.

My only disclaimer is that youll have to clone the repo and run your version locally, I probably won't bump the brew version or make a release for a while

**Comment by NGenetzky** [comment]
Thanks, I just have a desire to help provide user feedback to open source when I am able. Its not a big enough thorn in my side to run locally to get the fix - I will just wait for the next release.
Love to the project though; I am always using the terminal+keyboard and this sure beats trying to use tmux copy-mode.

**Comment by pcottle** [comment]
Glad you like the project! Thanks for dropping by
