### ISSUE TITLE
dual pane editing?

### ISSUE THREAD

**Issue by eriktux** [facebook/PathPicker#281]
Hi there,

I am new to FPP and though I have tried a few things, I can't find how you guys can open two files simultaneously for editing?

Just like you do in this demo video:
(https://asciinema.org/a/19519)
You select two js files, then you press "something" on your keyboard and boom!
You can edit both files, each in its own pane!

What's the keypress you use to achieve this?

Thanks  :)

**Comment by pcottle** [comment]
I just “enter” which will by default launch your editor with the two files listed. If your editor is vim, it does some additional magic to specify the argument to split the files in two panes.

Do you know what your editor variable is in bash?

**Comment by eriktux** [comment]
Well well, it seems like my EDITOR was set to "nano -Wm".
I know, nano isn't the best, it's just that I always found it to be more intuitive.

So, I have set my $EDITOR env variable to vim, and boom!  it works like you said  :+1: 

I didn't dive into vim yet, because there's a bit of a learning curve.  I have cheat-sheets for vim, ebooks, and video tutorials.  Time for me to get started, I guess!

Thanks for your help!

**Comment by pcottle** [comment]
Awesome! Glad you're unblocked.

I actually recommend this VIM videogame/adventure for rampup:
https://vim-adventures.com/

Way more fun than the books imo :)

**Comment by Ziggoto** [comment]
Is there a way to force open all file as buffers but with a single one pane?
