### ISSUE TITLE
--invoke-all option?

### ISSUE THREAD

**Issue by jamesalbert** [facebook/PathPicker#286]
is there anyway to invoke a command on all acceptable input? For example:

`ls images/ | fpp -c "docker build -t $F $F" --invoke-all`

**Comment by pcottle** [comment]
Nope but you can hit “A” to select all input?

**Comment by pcottle** [comment]
Sure if you're comfortable with the code, a PR would be great! I figured most people just wanted the preconfigured command and then would select it manually.

So with `--invoke-all` and `-c` it wouldn't require any user input?

**Comment by jamesalbert** [comment]
@pcottle I've contributed to a ruby project here and there 😄I can at least take a look especially since this would fit a use case of mine gloriously. 

That would definitely be the goal
