### ISSUE TITLE
No linux Instructions

### ISSUE THREAD

**Issue by ddaza** [facebook/PathPicker#29]
where is the love?

**Comment by pcottle** [comment]
Hey @ddaza,

You should find some linux instructions in the projects README:
> However if you're on a system without Homebrew, it's still quite easy to install PathPicker since it's essentially just a bash script that calls some Python. These steps more-or-less outline the process:

https://github.com/facebook/PathPicker

We recently added linux support with the `python2` command detection (not part of the public release yet) and are working on a linuxbrew recipe as well.
