### ISSUE TITLE
File not selectable when path contains 2 spaces

### ISSUE THREAD

**Issue by KevCui** [facebook/PathPicker#297]
fpp version 0.7.2

fpp cannot select the file which path/name contains 2 spaces:

![1546956156](https://user-images.githubusercontent.com/14293537/50835262-84f0ce80-1356-11e9-8080-118a5ec5faaa.jpg)

In this case, these files are not selectable:
```
  folder4/file1.md
folder  5/file5.md
folder2/file  2.md
```

**Comment by pcottle** [comment]
Yeah sadly we don't support more than once space in filenames. this is because shell utilities often use spaces to delimit between results, so it's a big ambiguous if this is all one filepath or separate sets of data :/
