### ISSUE TITLE
breaks when the file path contains duplicate dir names

### ISSUE THREAD

**Issue by Chandler** [facebook/PathPicker#3]
git diff --stat
 tweets/server/src/main/scala/com/twitter/tweets/Tweets.scala   | 17 +++++++++++++---

git diff --stat | fpp
 .../tweets/Tweets.scala     | 17 ++++-

when you navigate to the item in fpp it attempts to open .../tweets/Tweets.scala which doesn't exist. The full path that's printed out when not using fpp is the correct path.

**Comment by pcottle** [comment]
Yeah this is unfortunately an issue with git's output when it (thinks) there is not much space on the terminal. It truncates the path to `.../` (notice the three dots) which basically blasts away all information about the path.

@jingc ran into this as well, not sure what we can do here

**Comment by Chandler** [comment]
I couldn't figure out how to make git diff --stat use fully qualified paths but there are some other commands that do work.

git diff --numstat HEAD~1 | fpp

git diff --name-status HEAD~1 | fpp

**Comment by pcottle** [comment]
Yeah I checked the man pages, `--numstat` should not abbreviate the path names;

```
       --numstat
           Similar to --stat, but shows number of added and deleted lines in decimal notation and pathname without abbreviation, to make it
           more machine friendly. For binary files, outputs two - instead of saying 0 0.
```

Closing out since we can't do much here besides suggest `--numstat` if we detect a `.../` pathname, and I'd be worried about that being noisy. Do you think that's worth adding?

**Comment by Chandler** [comment]
I ran into this error the very first time I tried fpp and spent a few min trying to figure it out so I imagine the hint would be pretty useful. Especially if we are sure that "..." is only used to indicate truncation and not a valid path (... is technically valid).

Could just put a note about the --stat issue in the readme, since --stat is the example used in the demo.

**Comment by pcottle** [comment]
Yeah lets *at least* do the readme thing. I'll see what I can do in the meantime though, since it is pretty confusing. ideally we actually output an error...

**Comment by pcottle** [comment]
getting there...

![screen shot 2015-05-07 at 4 55 50 pm](https://cloud.githubusercontent.com/assets/1135007/7528241/ef931f3a-f4d9-11e4-9c69-7953b7ab5f44.png)

**Comment by pcottle** [comment]
![screen shot 2015-05-07 at 5 08 11 pm](https://cloud.githubusercontent.com/assets/1135007/7528389/ecd46c02-f4db-11e4-844d-e9eb11cfac09.png)
![screen shot 2015-05-07 at 5 07 53 pm](https://cloud.githubusercontent.com/assets/1135007/7528390/ecd86e1a-f4db-11e4-8fdb-38dba9d20cdf.png)

^^ alright that should be a huge improvement
