### ISSUE TITLE
Does not handle paths with "@" in filename

### ISSUE THREAD

**Issue by davidgorges** [facebook/PathPicker#30]
Does not work if the filename contains "@" - which is often the case for retina size images.

## Input:
``../images/logo@2x.png`` 

## Pickable:
``2x.png``

## Expected:
``../images/logo@2x.png``

**Comment by groomsy** [comment]
Ditto for filenames containing '+' (Objective-C categories anyone?).

**Comment by pcottle** [comment]
Thanks for the file @davidgorges ! I just pushed a fix now with some test coverage, this will make it into the next release :tada:
