### ISSUE TITLE
FPP does not recognise filenames inside parenthesis

### ISSUE THREAD

**Issue by snoblenet** [facebook/PathPicker#303]
This works: `file.txt`.

This does not work: `(file.txt)`.

Perhaps related but different: https://github.com/facebook/PathPicker/issues/200

This is highly desirable because of https://v8.dev/docs/stack-trace-api

**Comment by pcottle** [comment]
Ah good point about the v8 stack traces. However those are just filenames and not file paths right? if you aren't in the same directory as that file, `fpp` won't help much

**Comment by snoblenet** [comment]
It's a mix. The [docs on Node 10](http://snoblenet.local:50129/Dash/uuiiaake/nodejs/api/errors.html#errors_error_stack) say:

> The location information will be one of:
> - native, if the frame represents a call internal to V8 (as in [].forEach).
> - plain-filename.js:line:column, if the frame represents a call internal to Node.js.
> - /absolute/path/to/file.js:line:column, if the frame represents a call in a user program, or its dependencies.

**Comment by pcottle** [comment]
Ah, well then we can support the third pretty quickly!

**Comment by pcottle** [comment]
It doesn't match on `(file.txt)` but should match on `(./file.txt)`, or absolute path versions of that :)
