### ISSUE TITLE
BashRC

### ISSUE THREAD

**Issue by soheil** [facebook/PathPicker#34]
It'd be nice to load up your .bachrc and .bash_profile in command mode so you can use your aliases etc.

**Comment by pcottle** [comment]
We do load up the bashrc and check for aliases:

https://github.com/facebook/PathPicker/blob/master/src/output.py#L109

Is something else not working? What format are you aliases in?

(closing for now, open up again if you have a solid repro)

**Comment by soheil** [comment]
I have a `ll` alias to do `ls -l` it didn't work...

**Comment by cosinequanon** [comment]
I can repro this. I have `source $HOME/.bash_aliases` in my .bashrc and in .bash_aliases I have `alias g="git "`

Go to a git repository, and enter:
`touch foo.txt`
`ls -l ./foo.txt | fpp`
then press c and enter `g add`

I get the error: `/home/sgoder/.fbPager.sh: line 4: g: command not found`

**Comment by pcottle** [comment]
>  I have source $HOME/.bash_aliases in my .bashrc and in .bash_aliases I have alias g="git "

yeah unfortunately we don't do recursive follows / sources :*( do either of you know if we could get bash to either:
  * give us the expanded format of a given alias
or even
  * give us the entire concat of the bashrc file
?

let me try this inside the command script instead...

**Comment by shaneharter** [comment]
@pcottle Can't you just use `alias` ?

**Comment by pcottle** [comment]
@shaneharter `alias` does not work inside shell scripts:

```
[pcottle:~/Desktop:]$ alias | wc -l
      54
[pcottle:~/Desktop:]$ echo "alias; echo 'alias is'; alias | wc -l" > ./test.sh 
[pcottle:~/Desktop:]$ sh ./test.sh
alias is
       0
```

unless you run with some weird mode, but that doesnt work for zsh

**Comment by shaneharter** [comment]
@pcottle Yeah i saw that after, sorry for the distraction :) Been using fpp for a few days now, :+1:

**Comment by Addisonbean** [comment]
Is there a way to prevent it from sourcing my .zshrc? My .zshrc prints something every time it is executed and that can get annoying if I'm not starting up a new shell.

**Comment by pcottle** [comment]
I somewhat have this issue as well, but I have a global flag to toggle it off. Basically I automatically ssh to my devserver at facebook unless I set a "local mode" flag

What does yours do? We could add (yet another) environment variable for this but I'm curious what the use case is.

**Comment by Addisonbean** [comment]
Oh yeah that's smart, thanks. Haha I just have this line in my .zshrc: `fortune | cowsay | lolcat` So I get a random fortune every time I start a new shell.

**Comment by pcottle** [comment]
Haha, maybe  I should do something similar. Terminal startups should be more fun!
