### ISSUE TITLE
How do I install this on Ubuntu?

### ISSUE THREAD

**Issue by diwu1989** [facebook/PathPicker#37]
I have ubuntu, how do I install this?
Also, can I install this on mac via Macports?

**Comment by pcottle** [comment]
We are hopefully going to get synced to:
https://github.com/Homebrew/linuxbrew

Soon! So that will be the main way. The alternative is to install manually with the options listed in the README:
https://github.com/facebook/PathPicker/blob/master/README.md

**Comment by Daniel15** [comment]
I don't know anyone that uses Linuxbrew, seems pretty odd to use that rather than actual packages. Would be good to have this packaged up and pushed to Debian/Ubuntu (and/or your own package source)
