### ISSUE TITLE
Python 3.0 compatibility 

### ISSUE THREAD

**Issue by dannguyen** [facebook/PathPicker#4]
I'm on 10.10.3. Ran `brew install fpp` and then `fpp`, and got this:

```
File "/usr/local/Cellar/fpp/0.5.3/libexec/src/processInput.py", line 126
    print USAGE_STR
                  ^
SyntaxError: Missing parentheses in call to 'print'
  File "/usr/local/Cellar/fpp/0.5.3/libexec/src/choose.py", line 54
    print 'Nothing to do!'
                         ^
SyntaxError: Missing parentheses in call to 'print'
sh: /Users/dan/.fbPager.sh: No such file or directory
```

**Comment by pcottle** [comment]
What version of python are you running? `python --version`. It's likely a Python 3.0 compatibility issue

**Comment by dannguyen** [comment]
Ah yes, I'm on Python 3.x

**Comment by pcottle** [comment]
PR #15 helped this a bit as well in the meantime -- @dannguyen @vimeitor have either of you tried that yet?

Let me see what the python 2to3 converter says...

**Comment by vimeitor** [comment]
@pcottle I can confirm that it works very well. It's a good first step for sure :).

**Comment by sdornan** [comment]
Would love for this to be compatible with Python 3.
