### ISSUE TITLE
fpp-git on AUR is quite outdated

### ISSUE THREAD

**Issue by KevCui** [facebook/PathPicker#402]
In README.md file installation on Arch Linux part, it points to [the package on AUR page](https://aur.archlinux.org/packages/fpp-git/). However, the package there is quite outdated: `Last Updated: 2018-11-21 16:42`. An update of this AUR package will be appreciated. :pray:

**Comment by thiagowfx** [comment]
Adopted and updated.

**Comment by KevCui** [comment]
@thiagowfx thanks!
