### ISSUE TITLE
New release before EOY?

### ISSUE THREAD

**Issue by thiagowfx** [facebook/PathPicker#412]
Hi, is there any chance we could have a new release before the end of the year? The latest release (0.9.2) is from more than 2 years ago and it's missing a few improvements that happened ever since.

Rationale: I was recently packaging [`fpp` for Alpine Linux](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/28364) and realized how much 0.9.2 differs from `master`. The way to run tests is also completely different (testing is one of the steps for creating a package for Alpine). And finally, the man page is more up-to-date (#403).

Thanks!

**Comment by pcottle** [comment]
hey all! sorry for the really weak ownership here -- I don't really have the bandwidth to maintain this project at work now so it needs some serious love.

I vaguely remember how to update the `brew` recipe but @thiagowfx you want the debian package right? I wasn't ever able to build the debian one myself, but I'll gladly take any PRs

**Comment by thiagowfx** [comment]
Thanks for your reply — I was mostly looking for a new point release (0.9.3 or 0.10) so that I could update the Arch and Alpine Linux packages with the recent changes (which are somewhat significant). I’m not much familiar with Debian.

**Comment by pcottle** [comment]
Oohhh I see what you mean! I just add a 0.9.5 release here:
https://github.com/facebook/PathPicker/releases/tag/0.9.5

if you send me the packages, I could add them/upload them to the release!

**Comment by thiagowfx** [comment]
Thank you, Peter! I've updated the Alpine Linux package[1] and flagged the one in the AUR[2] as out-of-date.

[1]: https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/30920
[2]: https://aur.archlinux.org/packages/fpp

**Comment by Deckluhm** [comment]
Both archives contain version `0.9.2` instead of `0.9.5`.

I don't know how releases work in GitHub but I guess it's because `0.9.5` tag contains the wrong code:

- https://github.com/facebook/PathPicker/blob/0.9.5/fpp.rb#L8
- https://github.com/facebook/PathPicker/blob/0.9.5/pyproject.toml#L24
- https://github.com/facebook/PathPicker/blob/0.9.5/src/version.py#L6

**Comment by HenrikBengtsson** [comment]
If it's just that the wrong commit was tagged 0.9.5, then one can remove the tag (locally and on GitHub) and set the tag to the correct commit and re-push. That should rebuild the tag on GitHub
