### ISSUE TITLE
fpp not opening files in $EDITOR

### ISSUE THREAD

**Issue by Zane-** [facebook/PathPicker#420]
Hello,

I have my $EDITOR set to vim, however when I attempt to open a file using `fpp`, it opens in `nano` instead.

Here's a video reproduction:
https://user-images.githubusercontent.com/6345012/163692696-1ca19d72-12a6-47b9-b565-ca8d6cf4e805.mp4

**Comment by Zane-** [comment]
Thought it might be using `$VISUAL`, which was set to `nano`, but I've changed that to `vim` as well, and still opening in nano.

**Comment by Deckluhm** [comment]
If you didn't already read that, maybe that can help:
> The $FPP_EDITOR environment variable can be set to tell PathPicker which editor to open the selected files with. If that variable is not set, $VISUAL and then $EDITOR are used as fallbacks, with "vim" as a last resort.

Also, be sure to restart your terminal after updating an environment variable.

**Comment by Zane-** [comment]
I set that variable, and it works now, but I'll still keep this open as it didn't pick any of the fallbacks, nor the last resort.

**Comment by Deckluhm** [comment]
Are you sure `$FPP_EDITOR` wasn't already defined elsewhere? (maybe not by you but by a plugin or something like that)

**Comment by Zane-** [comment]
I ripgrep'd my whole system, no results. I'm using a tmux-fpp plugin, but it doesn't set it anywhere (and I was also able to reproduce this outside of tmux)

**Comment by Deckluhm** [comment]
https://github.com/tmux-plugins/tmux-fpp/issues/18

It doesn't seem to be an issue with PathPicker but rather with tmux (and how it handles environment variables).

**Comment by Zane-** [comment]
Works now that I've moved the `EXPORT` statements above tmux's execution in my `.zshrc`. Thanks!
