### ISSUE TITLE
line selection mode

### ISSUE THREAD

**Issue by 20after4** [facebook/PathPicker#44]
Detecting paths is cool and everything, but I think it would be even more useful if there was a mode that treats every full input line as a "filename" (or other single parameter) and passes all selected lines to the output command, either one-by-one, or space-separated on the command line.

If this sounds useful to anyone else, I'll try to implement it and submit a pull request. It definitely seems to me like an entirely useful mode of operation.

By the way, thanks for fpp, it's a really awesome tool.

**Comment by Lbatson** [comment]
+1. it's great so far but this would be very useful

**Comment by beno2832** [comment]
stop

**Comment by pcottle** [comment]
glad you like the tool @20after4 ! As discussed in #69, we probably dont be going back towards a unixy mode of just outputting lines, but [fzf](https://github.com/junegunn/fzf) would be a great tool to look at!

I'll followup with how to do this in a local PR in #69
