### ISSUE TITLE
fpp doesn't pass path to command properly for paths in the top dir w/out ./ prefix

### ISSUE THREAD

**Issue by Ramblurr** [facebook/PathPicker#47]
The output of `ack -l` or `grep -l` that lists as demonstrated below is parsed properly by fpp (the interactive selection works), but when you execute a command on it (for example open the editor) it doesn't pass the proper path.

In the case of the first file listed below, fpp passes the following to vim:

/home/user/**www**/system-images/android-22/default/x86_64

when the proper path is:

/home/user/**vendor/android/sdk/**system-images/android-22/default/x86_64/source.properties

1. The CWD is /home/user/vendor/android/sdk/
2. I have no idea where the *www/* is coming from

```
ack xml -l | head                                                                                                                                                                    130 ↵
system-images/android-22/default/x86_64/source.properties
system-images/android-22/default/x86_64/NOTICE.txt
system-images/android-22/google_apis/x86_64/source.properties
system-images/android-22/google_apis/x86_64/NOTICE.txt
system-images/android-21/default/x86_64/source.properties
system-images/android-21/default/x86_64/NOTICE.txt
system-images/android-21/google_apis/x86/source.properties
system-images/android-21/google_apis/x86/NOTICE.txt
system-images/android-21/google_apis/x86_64/source.properties
system-images/android-21/google_apis/x86_64/NOTICE.txt
```

**Comment by Haraldson** [comment]
Experiencing the same. When pwd is `~/www/project/`, and I select a file and try running the command `git add` on it, PathPicker is attempting to add the file `~/www/src/app/app.js`, while the proper path would be `~/www/project/www/src/app/app.js`.

**Comment by CatTail** [comment]
+1

**Comment by pcottle** [comment]
> I have no idea where the www/ is coming from

Yeah, we throw in the random `www/` since thats the fallback for the facebook dev environment. its a giant hack though and super vestigial, so it should be removed regardless.

Question for you @Haraldson / @Ramblurr  -- are you guys working in folders with version control? We should parse the top-level directory from version control and use that for the prepend:

https://github.com/facebook/PathPicker/blob/master/src/parse.py#L38-L66

in the meantime ill fallback to `./`

**Comment by pcottle** [comment]
I guess the weird thing is that we will output paths with `./` but they are still valid:

```
[pcottle:~/Dropbox (Facebook):]$ cat ./wip/./../wip/PathPicker/././src/choose.py  | wc -l
      85
```

@Haraldson / @Ramblurr its important to note though that the input you guys listed above is lacking some context on where the actual path is. with this change we'll assume `./system-images/android-21/google_apis/x86_64/NOTICE.txt` is a valid file, but for commands like `git grep` thats not always valid

**Comment by pcottle** [comment]
In the 0.5.7 release, adding PR to homebrew now:
https://github.com/facebook/PathPicker/releases/tag/0.5.7
