### ISSUE TITLE
Allow use of shell aliases

### ISSUE THREAD

**Issue by raine** [facebook/PathPicker#51]
I have a ton of git aliases and would like to use them with command mode. Otherwise the mode is practically worthless.

`fbPager.sh: line 4: gco: command not found`

**Comment by joeguilmette** [comment]
a big +1 from me

**Comment by pcottle** [comment]
Alright I heard back about my approach in #59 so lets go with that! My only worry is that we source the entire `.bashrc` which might have side-effects. I actually use my bashrc to log onto my development server for facebook (automatically) so its kind of an aggressive script to source, but hopefully my situation is not super common.

```
[pcottle:~/Dropbox (Facebook)/wip/PathPicker:master]$ git show --stat | ./fpp
getting input
executing command:
ga  '/Users/pcottle/Dropbox (Facebook)/wip/PathPicker/src/output.py'
```
(`ga` is aliased to git add for me)

should work 100% for bash, and hoping zsh is the same way. can anyone test?

**Comment by langtianlang** [comment]
@pcottle Using 0.5.6. Zsh aliases did not work for me

```
➜  code/stuff git:(master) ✗ gs | fpp
getting input
executing command:
ga '/Users/llang/code/stuff/thing.rb'
/Users/llang/.fpp/.fpp.sh: line 4: ga: command not found
➜  code/stuff git:(master) ✗ brew upgrade fpp
Error: fpp 0.5.6 already installed
➜  code/upclookup git:(master) ✗ ga
Nothing specified, nothing added.
Maybe you wanted to say 'git add .'?
```

**Comment by pcottle** [comment]
@langtianlang youll have to install from master, since 0d12fef0bcfd3e2c4ac2e4e72af7f35041931c7e is not in fpp `0.5.6`:

```
# excerpt from 0.5.6's output.py
def getAliases():
    try:
        lines = open(os.path.expanduser(BASH_RC), 'r').readlines()
    except IOError:
```

either follow the manual install instructions in the README or wait till tonight when I submit the new release :)
