### ISSUE TITLE
Git installation troubles

### ISSUE THREAD

**Issue by cboden** [facebook/PathPicker#6]
I have a couple issues with the installation via git. I'm on OS X 10.10.3 with Python 2.7.6.

1) The installation instructions create a cyclic symbolic link: `ls -ltr | tail -n 1`
> lrwxr-xr-x (etc) fpp -> ./fpp

Adjusting the `ln` command to use the full path for the source fixes that.

2) After the symbolic link is setup correctly I get the following error when running `fpp --help`:
> /usr/local/bin/fpp: line 18: cd: /usr/local/bin//usr/local/PathPicker: No such file or directory
python: can't open file '/src/printHelp.py': [Errno 2] No such file or directory

I have placed PathPicker in `/usr/local/PathPicker` and linked the binary to `/usr/local/bin/fpp`.

**Comment by kkoch986** [comment]
had the exact same experience, fixed by changing 

```
while [ -h "$WHEREAMI" ]; do
  WHEREAMI=$(dirname "$WHEREAMI")"/"$(readlink "$WHEREAMI")
done
```

to 

```
while [ -h "$WHEREAMI" ]; do
  WHEREAMI=$(readlink "$WHEREAMI")
done
```

**Comment by frantic** [comment]
@cboden, @kkoch986 - could you please try #16 and see if it works for you?

**Comment by kkoch986** [comment]
works for me

**Comment by cboden** [comment]
works for me as well
