### ISSUE TITLE
Allow selection of items interactively with search keywords

### ISSUE THREAD

**Issue by bradparks** [facebook/PathPicker#66]
The basic idea is great... But manually picking a bunch of items is ok, but you should also be able to interactively search for items to add to the selection list. Why? Because sometimes, you have *alot* of matching files, and manually picking them is tedious. Regex's are ok, but only basic regexs are what 99% of people understand. Think as simple as *.* or *.jpg, or *.js, and you've reached 90% of the understanding of the regex crowd.

For example, say I was in interactive mode, and had selected a few files by hitting `f` on each file.

I should also be able to enter "search mode" by typing `/` and then specifying a search query like the following:

`test ez ab super$ ^black`

which would match any file that has:
- the words `test`, `ez`, `ab` in their filename
- begins with the world `black`
- ends with the word `super`

- the results of this search would be shown in a filtered search result, and users could select matching items in this sub search by using the `f` shortcut.

If you did this.... this tool would be extra awesome!

**Comment by pcottle** [comment]
Hey @bradparks, thanks for your interest in the project!

We do have the `A` shortcut which will toggle **all** the files' selection mode, so thats at least something you can use when you have a lot of files.

Regex and fuzzy searching did come up earlier when we were brainstorming the project, but we decided to stick to path matching early on to not try to do too many things at once. We're already criticized for doing too many things (its not unixy) so adding fuzzy search would make that worse. Besides I think excellent tools like [fzf](https://github.com/junegunn/fzf) would be a better match, or you could simply just process the input before sending it into fpp.

Closing it out for now but an interesting idea, its all about striking a balance
