### ISSUE TITLE
Offer a pure Python alternative script 

### ISSUE THREAD

**Issue by sametmax** [facebook/PathPicker#74]
I don't know if you are ok with replacing the shell script with a pure Python script, but even if you prefer to have the shell part, at least provide a pure Python version as an alternative.

This way you can us the tool under windows, and for any shell flavor (bash, sh, zsh, shell fish, etc).

In the end, i feel like it would be easier to get rid of the bash part completely though, since you can make a Python code working on any Python version, you can make it easily install a command (even if you don't have homebrew) and it's way simpler to unit test.

**Comment by SamHasler** [comment]
I think they're more likely to rewrite it in JavaScript than Python give what pcottle said in https://github.com/facebook/PathPicker/issues/56#issuecomment-100743171

**Comment by pcottle** [comment]
Yeah as @SamHasler said, closing this out for now. with react native proving how react transcends the web platform, im hoping that curses version shows up soon
