### ISSUE TITLE
False positive on `and/or`

### ISSUE THREAD

**Issue by markjaquith** [facebook/PathPicker#75]
As part of its output, `git status` prints this:

`use "git add" and/or "git commit -a"`

PathPicker picks up `and/or` as a path. I don't know if excluding `and/or` specifically is a good idea, but given the popularity of git, I think that `use "git add" and/or "git commit -a"` could be specifically excluded.

**Comment by eduardtm** [comment]
I ran into the same issue during my first minutes of using fpp, +1

**Comment by pcottle** [comment]
Yeah false positives don't really hurt you, but they are less than ideal. lets merge this into #83 which tracks the filesystem validation side
