### ISSUE TITLE
navigate by text line, not matched line

### ISSUE THREAD

**Issue by lastquestion** [facebook/PathPicker#76]
I'd like to be able to navigate up and down by line, and not automatically jump to the next line match. I'd imagine we could add a mode to flip the navigation keys into, or maybe alternately add new keys.

I'd prefer the former. I'd also like it to be a --command-line-switch so it can be passed in all the time.

I'll submit a PR for this sometime soon, as it would make path picker easier to use for me. Unless someone objects strongly, I'll implement a text-mode versus a match-mode, and have a key to flip between the two, and a command line option. And update the docs. and add it to the menu. Whew.

**Comment by pcottle** [comment]
I actually think this is one of the best features of PathPicker -- tools like `less` don't understand whats a file and whats not, so they require you to page through everythinggggggg instead of just what you might be interested in.

Especially for inputs like `git diff` where the filenames are really spread out, the quick jump is quite helpful imo

I'll close out for now, but I'd be interested in seeing a PR for this since it shouldn't be terribly hard to built (unless you wanted to decorate the simple line that was matched)

**Comment by lastquestion** [comment]
Actually, the only reason I want this is for things like `git diff | fpp` where I want to examine every line of the diff and if a diff has an issue, I want to quickly open the corresponding file. 

If I go from one link to another right now, I might lose half a page of diff that I can't read because the diff for the previous file is so big that it spans multiple pages.  In that case, I'd have to open up `git diff` and then remember which files I wanted to touch and then open up `git status` and then `fpp` on that? 

Hm, actually 90% of the time I actually probably want page up/down by page, and then up|down on matched line. 

It might be confuzzling but another option I'd probably want to prototype out as well is "navigate on matched lines and then page per page". Terrible description, but what I mean is, up|down move the cursor thru matched lines until it can't find another one on the same page. Then it moves the page forward and shows the next text page, and then you nagivate thru that. It's more of a change to the scroll algorithm.

However this might mean you would scroll to a page w/ no matched text and then you're forced to press down again. And in a very big input I'm not sure if this is better or worse.

**Comment by lastquestion** [comment]
How do you deal with the situation where when you're looking at `git diff` the next link forces fpp to scroll down so much you miss some diff?
