### ISSUE TITLE
I made tmux-fpp. Any interest in adding a link to the README?

### ISSUE THREAD

**Issue by jbnicolai** [facebook/PathPicker#79]
I created a tmux wrapper around PathPicker:

[![Demo tmux-fpp](http://g.recordit.co/MhLPNgOKyN.gif)](http://recordit.co/MhLPNgOKyN)

Would you be interested in adding a link to the README? Or plugging this somewhere else?

And if you guys have any feedback, feel free!

**Comment by mahamudul007** [comment]
Duoss4462@gmail.com

**Comment by pcottle** [comment]
Yeah I'm interested @jbnicolai  -- can you link the source somewhere? Also I'm curious -- when running `fpp` normally in tmux, what is broken versus what does your script fix? We are working on getting color support in #53 which is the only thing I can think of that might be weird

**Comment by jbnicolai** [comment]
@pcottle Oops, can't believe I forgot to link it when creating the issue. [Here](jbnicolai/tmux-fpp) it is!

When running fpp normally in tmux it works exactly as expected. However, you have to remember to insert `fpp` in the pipeline when executing your command. What this plugin allows is for the user to press a key combination (`prefix + i`) and run fpp over the most recently created `stdout` and `stderr` in the active TTY.

If you look at this gif in the original issue you see `fpp` is never executed manually on `git diff`. The user ran `git diff`, realized he wanted to pick a path and pressed `prefix + i` afterwards.

**Comment by lastquestion** [comment]
@jbnicolai fyi your link is broken. actual link https://github.com/jbnicolai/tmux-fpp
random question, what happens if the output of the last command is greater then the screen buffer size?

**Comment by jbnicolai** [comment]
@lastquestion thank you, I fixed the link!

It will truncate it, I suppose. Good question, let me do some testing and report back :)
