### ISSUE TITLE
Piping detected filenames to next command

### ISSUE THREAD

**Issue by mknecht** [facebook/PathPicker#93]
Hey,

this simple command does not work:

    $ ls | fpp | echo

I'm getting this stuff: 

    close failed in file object destructor:
    sys.excepthook is missing
    lost sys.stderr

… while `ls | fpp` works just fine, and recognizes a bunch of paths.

Any reason not to support this? Combined with `xargs`, it would be a powerful tool.

Thanks!

murat

**Comment by lastquestion** [comment]
You can't pipe the output of a curses program, because curses uses `stdout` with control characters to print to the terminal.

You want this feature request: https://github.com/facebook/PathPicker/issues/72 I think.

**Comment by mknecht** [comment]
Hm, nah, what about detecting that stdout is a PIPE and thus not showing the curses interface, but just printing the detected paths to stdout. Would such a PR be accepted?

**Comment by pcottle** [comment]
Hey @mknecht, this has been discussed a pair amount before (see #69) -- I think going 100% unix philosophy actually detracts one of the main value adds of PathPicker which is that it's a one-stop shop for the whole workfow that progress in logical order.

I think something like https://github.com/mooz/percol does the "select and pipe" workflow really well, so if we switched to that we'd be an inferior version of that toll :P

The downside with "select and pipe" is that you have to compose your command ahead of time:

`git checkout $(git branch -va | percol)`
or
`rm -rf $(ls -l | percol)`

mentally you have to go from:
  * What input do I have? What am I going to select out? and then what command do I want to run?
  * Ok lets compose that command based on the subshell results of the input command piped to the picker

Whereas with PathPicker (imo) you just go:
  * I have some stdin -- lets pipe
  * Sweet, lets select this
  * I want to do.... this command (`/me types it in`)
  * boom!

It's more straightforward in my opinion. @KendallHopkins was asking about this last night at dinner.

Anyways closing out in the meantime, but I think #72 could work **really** well for the alias workflow
