### ISSUE TITLE
Lingering text bug

### ISSUE THREAD

**Issue by xavierbeynon** [facebook/PathPicker#98]
After unselecting an item, the trail of the selection text lingers
![demo](https://cloud.githubusercontent.com/assets/6413422/7626506/dbb7cf92-f9cf-11e4-8a1c-9e29116aef88.png)

**Comment by lastquestion** [comment]
I noticed this earlier today. It was introduced by color support. I will open a PR for it today or tomorrow. Thanks for the bug report.

**Comment by lastquestion** [comment]
Fixed in #100

**Comment by pcottle** [comment]
How can you guys repro this? I actually can't repro at all, with python2 or python3.

**Comment by lastquestion** [comment]
I need to fix up that PR.... 

Try to generate an input with one match at the end of the line. it should show up on a git diff for example.

**Comment by pcottle** [comment]
![screen shot 2015-05-15 at 6 48 54 pm](https://cloud.githubusercontent.com/assets/1135007/7664238/0d7b4324-fb33-11e4-9049-fe18d6a0f481.png)

ah I see :P quite subtle!

**Comment by pcottle** [comment]
Done! Thanks @lastquestion for the majority of the fix -- wanted to get this in ASAP before the weekend, since we just took out a bunch of Facebook ads for path picker and dont want any bugs if they install from master

**Comment by lastquestion** [comment]
LOL did you really? I hope you aren't paying too much CPM. ^) Thanks, I'll look at your implementation now and follow up on everything that's happened, I saw your PRs. Thanks again for using PRs, it lets people follow along and understand the code evolution even if they can't get to stuff right that minute.
